#!/bin/bash

# https://bugs.winehq.org/show_bug.cgi?id=53174
if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor deaf0891b096628cf99e58834c39a45a6c99c54c HEAD ); then
  warning "Hotfix: Workaround Star Citizen launcher hang due to low heap space"
  _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/larger_def_heap/larger_def_heap)
fi
