#!/bin/bash

_apply_GE_patch() {
    msg2 "Applying ${_patchname}"
    echo -e "\nApplying $_patchname" >> "$_where"/prepare.log
    patch -Np1 < "$_patchpath/$_patchname" >> "$_where"/prepare.log
}

_GE() {
    msg2 "GE patches..."
    _patchname="assettocorsa-hud.patch" _patchpath="$_where/wine-tkg-patches/hotfixes/GE/game-patches" _apply_GE_patch
    #_patchname="mk11.patch" _patchpath="$_where/wine-tkg-patches/hotfixes/GE/game-patches" _apply_GE_patch
    _patchname="killer-instinct-winevulkan_fix.patch" _patchpath="$_where/wine-tkg-patches/hotfixes/GE/game-patches" _apply_GE_patch
    _patchname="FFVII-and-SpecialK-powerprof.patch" _patchpath="$_where/wine-tkg-patches/hotfixes/GE/game-patches" _apply_GE_patch

    if [ "$_GE_FSR" = "true" ]; then
      if [[ "$_LOCAL_PRESET" = valve-exp* ]]; then
        _ge_subpath="/exp-be"
      fi
      _patchname="48-proton-fshack_amd_fsr.patch" _patchpath="$_where/wine-tkg-patches/hotfixes/GE/proton$_ge_subpath" _apply_GE_patch
      _patchname="65-proton-fake_current_res_patches.patch" _patchpath="$_where/wine-tkg-patches/hotfixes/GE/proton$_ge_subpath" _apply_GE_patch
      _patchname="69-proton-fsr-add-329-res.patch" _patchpath="$_where/wine-tkg-patches/hotfixes/GE/proton$_ge_subpath" _apply_GE_patch
      _patchname="70-proton-add_fsr_res_by_aspect_ratio.patch" _patchpath="$_where/wine-tkg-patches/hotfixes/GE/proton$_ge_subpath" _apply_GE_patch
    fi

    _patchname="unity_crash_hotfix.patch" _patchpath="$_where/wine-tkg-patches/hotfixes/GE/wine-hotfixes/pending" _apply_GE_patch
    _patchname="Fix-regression-introduced-by-0e7fd41.patch" _patchpath="$_where/wine-tkg-patches/hotfixes/GE/wine-hotfixes/upstream" _apply_GE_patch
    _patchname="15aa8c6-fix-star-citizen-bug-52956.patch" _patchpath="$_where/wine-tkg-patches/hotfixes/GE/wine-hotfixes/upstream" _apply_GE_patch
    _patchname="0001-winex11.drv-Define-ControlMask-when-not-available.patch" _patchpath="$_where/wine-tkg-patches/hotfixes/GE/wine-hotfixes/pending" _apply_GE_patch
    _patchname="0002-include-Add-THREAD_POWER_THROTTLING_STATE-type.patch" _patchpath="$_where/wine-tkg-patches/hotfixes/GE/wine-hotfixes/pending" _apply_GE_patch
    _patchname="0003-ntdll-Fake-success-for-ThreadPowerThrottlingState.patch" _patchpath="$_where/wine-tkg-patches/hotfixes/GE/wine-hotfixes/pending" _apply_GE_patch
}
