#!/bin/bash

_GE() {
    msg2 "GE patches..."
    patch -Np1 < "$_where"/wine-tkg-patches/hotfixes/GE/game-patches/assettocorsa-hud.patch
    #patch -Np1 < "$_where"/wine-tkg-patches/hotfixes/GE/game-patches/mk11.patch
    patch -Np1 < "$_where"/wine-tkg-patches/hotfixes/GE/game-patches/killer-instinct-winevulkan_fix.patch
    patch -Np1 < "$_where"/wine-tkg-patches/hotfixes/GE/game-patches/FFVII-and-SpecialK-powerprof.patch

    patch -Np1 < "$_where"/wine-tkg-patches/hotfixes/GE/proton/65-proton-fake_current_res_patches.patch

    patch -Np1 < "$_where"/wine-tkg-patches/hotfixes/GE/wine-hotfixes/pending/unity_crash_hotfix.patch
    patch -Np1 < "$_where"/wine-tkg-patches/hotfixes/GE/wine-hotfixes/upstream/Fix-regression-introduced-by-0e7fd41.patch
    patch -Np1 < "$_where"/wine-tkg-patches/hotfixes/GE/wine-hotfixes/upstream/15aa8c6-fix-star-citizen-bug-52956.patch
    patch -Np1 < "$_where"/wine-tkg-patches/hotfixes/GE/wine-hotfixes/pending/0001-winex11.drv-Define-ControlMask-when-not-available.patch
    patch -Np1 < "$_where"/wine-tkg-patches/hotfixes/GE/wine-hotfixes/pending/0002-include-Add-THREAD_POWER_THROTTLING_STATE-type.patch
    patch -Np1 < "$_where"/wine-tkg-patches/hotfixes/GE/wine-hotfixes/pending/0003-ntdll-Fake-success-for-ThreadPowerThrottlingState.patch
}
