#!/bin/bash

_GE() {
    msg2 "GE patches..."
    _patchname="assettocorsa-hud.patch" && patch -Np1 < "$_where"/wine-tkg-patches/hotfixes/GE/game-patches/$_patchname >> "$_where"/prepare.log && msg2 "Applying ${_patchname}"
    #_patchname="mk11.patch" && patch -Np1 < "$_where"/wine-tkg-patches/hotfixes/GE/game-patches/$_patchname >> "$_where"/prepare.log && msg2 "Applying ${_patchname}"
    _patchname="killer-instinct-winevulkan_fix.patch" && patch -Np1 < "$_where"/wine-tkg-patches/hotfixes/GE/game-patches/$_patchname >> "$_where"/prepare.log && msg2 "Applying ${_patchname}"
    _patchname="FFVII-and-SpecialK-powerprof.patch" && patch -Np1 < "$_where"/wine-tkg-patches/hotfixes/GE/game-patches/$_patchname >> "$_where"/prepare.log && msg2 "Applying ${_patchname}"

    if [ "$_GE_FSR" = "true" ]; then
      _patchname="48-proton-fshack_amd_fsr.patch" && patch -Np1 < "$_where"/wine-tkg-patches/hotfixes/GE/proton/$_patchname >> "$_where"/prepare.log && msg2 "Applying ${_patchname}"
      _patchname="65-proton-fake_current_res_patches.patch" && patch -Np1 < "$_where"/wine-tkg-patches/hotfixes/GE/proton/$_patchname >> "$_where"/prepare.log && msg2 "Applying ${_patchname}"
      _patchname="69-proton-fsr-add-329-res.patch" && patch -Np1 < "$_where"/wine-tkg-patches/hotfixes/GE/proton/$_patchname >> "$_where"/prepare.log && msg2 "Applying ${_patchname}"
    fi

    _patchname="unity_crash_hotfix.patch" && patch -Np1 < "$_where"/wine-tkg-patches/hotfixes/GE/wine-hotfixes/pending/$_patchname >> "$_where"/prepare.log && msg2 "Applying ${_patchname}"
    _patchname="Fix-regression-introduced-by-0e7fd41.patch" && patch -Np1 < "$_where"/wine-tkg-patches/hotfixes/GE/wine-hotfixes/upstream/$_patchname >> "$_where"/prepare.log && msg2 "Applying ${_patchname}"
    _patchname="15aa8c6-fix-star-citizen-bug-52956.patch" && patch -Np1 < "$_where"/wine-tkg-patches/hotfixes/GE/wine-hotfixes/upstream/$_patchname >> "$_where"/prepare.log && msg2 "Applying ${_patchname}"
    _patchname="0001-winex11.drv-Define-ControlMask-when-not-available.patch" && patch -Np1 < "$_where"/wine-tkg-patches/hotfixes/GE/wine-hotfixes/pending/$_patchname >> "$_where"/prepare.log && msg2 "Applying ${_patchname}"
    _patchname="0002-include-Add-THREAD_POWER_THROTTLING_STATE-type.patch" && patch -Np1 < "$_where"/wine-tkg-patches/hotfixes/GE/wine-hotfixes/pending/$_patchname >> "$_where"/prepare.log && msg2 "Applying ${_patchname}"
    _patchname="0003-ntdll-Fake-success-for-ThreadPowerThrottlingState.patch" && patch -Np1 < "$_where"/wine-tkg-patches/hotfixes/GE/wine-hotfixes/pending/$_patchname >> "$_where"/prepare.log && msg2 "Applying ${_patchname}"
}
