#!/bin/bash

	# Set the default wine version to win10
	if [ "$_win10_default" = "true" ] && [ "$_unfrog" != "true" ] && git merge-base --is-ancestor 74dc0c5df9c3094352caedda8ebe14ed2dfd615e HEAD; then
	  if git merge-base --is-ancestor 863858da2aa42edfa3b4e639905fcad7056eaeb5 HEAD; then
	    _patchname='proton-win10-default.patch' && _patchmsg="Enforce win10 as default wine version" && nonuser_patcher
	  elif git merge-base --is-ancestor 69154f0329aec4fb64886a0689da198b5323dcde HEAD; then
	    _patchname='proton-win10-default-863858d.patch' && _patchmsg="Enforce win10 as default wine version" && nonuser_patcher
	  elif git merge-base --is-ancestor 3ec7c467cdc89200929cf738e19491182fb492a6 HEAD; then
	    if [ "$_use_staging" = "true" ] && ( cd "${srcdir}"/"${_stgsrcdir}" && ! git merge-base --is-ancestor 4303e3ee3b89fcb952e77938073b9911f0093377 HEAD ); then
	      _patchname='proton-win10-default-staging-69154f0.patch' && _patchmsg="Enforce win10 as default wine version (staging)" && nonuser_patcher
	    else
	      _patchname='proton-win10-default-69154f0.patch' && _patchmsg="Enforce win10 as default wine version" && nonuser_patcher
	    fi
	  elif git merge-base --is-ancestor c89ce41ec964c4f704bb12c8a8c6ab386372bae9 HEAD; then
	    if [ "$_use_staging" = "true" ]; then
	      _patchname='proton-win10-default-staging-3ec7c46.patch' && _patchmsg="Enforce win10 as default wine version (staging)" && nonuser_patcher
	    else
	      _patchname='proton-win10-default-3ec7c46.patch' && _patchmsg="Enforce win10 as default wine version" && nonuser_patcher
	    fi
	  elif git merge-base --is-ancestor d02d50299b236690738563e1db8c08d1cb603f76 HEAD; then
	    if [ "$_use_staging" = "true" ]; then
	      _patchname='proton-win10-default-staging-c89ce41.patch' && _patchmsg="Enforce win10 as default wine version (staging)" && nonuser_patcher
	    else
	      _patchname='proton-win10-default-c89ce41.patch' && _patchmsg="Enforce win10 as default wine version" && nonuser_patcher
	    fi
	  elif git merge-base --is-ancestor 39263558a2088940aaacd6eda19ca23d40b63495 HEAD; then
	    if [ "$_use_staging" = "true" ]; then
	      _patchname='proton-win10-default-staging-d02d502.patch' && _patchmsg="Enforce win10 as default wine version (staging)" && nonuser_patcher
	    else
	      _patchname='proton-win10-default-d02d502.patch' && _patchmsg="Enforce win10 as default wine version" && nonuser_patcher
	    fi
	  elif git merge-base --is-ancestor 595600b6c14c957d19f3ef8c0c82acacd7c6827a HEAD; then
	    if [ "$_use_staging" = "true" ]; then
	      _patchname='proton-win10-default-staging-3926355.patch' && _patchmsg="Enforce win10 as default wine version (staging)" && nonuser_patcher
	    else
	      _patchname='proton-win10-default-3926355.patch' && _patchmsg="Enforce win10 as default wine version" && nonuser_patcher
	    fi
	  elif git merge-base --is-ancestor 87f41e6b408dd01055ff6a378b90d089d61ec370 HEAD; then
	    if [ "$_use_staging" = "true" ]; then
	      _patchname='proton-win10-default-staging-595600b.patch' && _patchmsg="Enforce win10 as default wine version (staging)" && nonuser_patcher
	    else
	      _patchname='proton-win10-default-595600b.patch' && _patchmsg="Enforce win10 as default wine version" && nonuser_patcher
	    fi
	  elif git merge-base --is-ancestor e13d54665765d9dd8829233f0ea748fd685a1913 HEAD; then
	    if [ "$_use_staging" = "true" ]; then
	      _patchname='proton-win10-default-staging-87f41e6.patch' && _patchmsg="Enforce win10 as default wine version (staging)" && nonuser_patcher
	    else
	      _patchname='proton-win10-default-87f41e6.patch' && _patchmsg="Enforce win10 as default wine version" && nonuser_patcher
	    fi
	  else
	    _patchname='proton-win10-default-e13d546.patch' && _patchmsg="Enforce win10 as default wine version" && nonuser_patcher
	  fi
	fi
