#!/bin/bash

	# Workaround for Final Fantasy XIV Launcher 404 error - Thanks @varris1 ! - Fixed by d535df42f665a097ec721b10fb49d7b18f899be9 (4.10)
	if [ "$_ffxivlauncher_fix" = "true" ]; then
	  if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 9bf46d5ce608a97e264681d2637ff3105e42c363 HEAD ); then
	    _patchname='ffxiv-launcher-workaround.patch' && _patchmsg="Applied Final Fantasy XIV Launcher fix" && nonuser_patcher
	  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 0c249e6125fc9dc6ee86b4ef6ae0d9fa2fc6291b HEAD ); then
	    _patchname='ffxiv-launcher-workaround-9bf46d5.patch' && _patchmsg="Applied Final Fantasy XIV Launcher fix" && nonuser_patcher
	  elif ( cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor 4e6a477acd32651dd571205786132666505aeb5b HEAD ); then
	    _patchname='ffxiv-launcher-workaround-0c249e6.patch' && _patchmsg="Applied Final Fantasy XIV Launcher fix" && nonuser_patcher
	  else
	    _patchname='ffxiv-launcher-workaround-4e6a477.patch' && _patchmsg="Applied Final Fantasy XIV Launcher fix" && nonuser_patcher
	  fi
	fi
