#!/bin/bash

# Fix building not working wine with binutils 2.44
if ( cd "${srcdir}"/"${_winesrcdir}" && ! git merge-base --is-ancestor c9519f68ea04915a60704534ab3afec5ec1b8fd7 HEAD ); then
  _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/binutils/7328)
  warning "Hotfix: Fix building with binutils 2.44"
fi
