#!/bin/bash

	  if [ "$_staging_pulse_disable" != "true" ] && [ "$_use_staging" = "true" ] && ( cd "${srcdir}"/"${_winesrcdir}" && ! git merge-base --is-ancestor d3673fcb034348b708a5d8b8c65a746faaeec19d HEAD ); then
	    if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 8c0ced87bcec8bdc505bf844cc9247106ebd8c36 HEAD ); then
	      _patchname='proton-pa-staging.patch' && _patchmsg="Enable Proton's PA additions" && nonuser_patcher
	    elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor fa6d22b976214ff4dfb32b431500b4cd1f7610a0 HEAD ); then
	      _patchname='proton-pa-staging-8c0ced8.patch' && _patchmsg="Enable Proton's PA additions" && nonuser_patcher
	    else
	      _patchname='proton-pa-staging-fa6d22b.patch' && _patchmsg="Enable Proton's PA additions" && nonuser_patcher
	    fi
	  fi
