#!/bin/bash

	# Shared gpu resources patchset - https://github.com/doitsujin/dxvk/pull/2516
	if [ "$_shared_gpu_resources" = "true" ] && [ "$_childwindow_fix" = "true" ] && [ "$_use_staging" = "true" ] && git merge-base --is-ancestor c86955d3806879fc97b127730e9fb90e232710a7 HEAD; then
	  if git merge-base --is-ancestor c86955d3806879fc97b127730e9fb90e232710a7 HEAD; then
	    _patchname='sharedgpures.patch' && _patchmsg="Applied shared gpu resources patchset" && nonuser_patcher
	  fi
	  if git merge-base --is-ancestor c86955d3806879fc97b127730e9fb90e232710a7 HEAD; then
	    _patchname='sharedgpures-fixup.patch' && nonuser_patcher
	  fi
#	  if git merge-base --is-ancestor c86955d3806879fc97b127730e9fb90e232710a7 HEAD; then
#	    _patchname='sharedgpures-mfplat.patch' && nonuser_patcher
#	  fi
	fi
