#!/bin/bash
#c65bfc062bfe1e2256a814ec7a0286214da04b0e
	# Shared gpu resources support https://github.com/doitsujin/dxvk/pull/2516 https://github.com/doitsujin/dxvk/pull/2608 https://github.com/HansKristian-Work/vkd3d-proton/pull/1175
	if [ "$_shared_gpu_resources" = "true" ] && git merge-base --is-ancestor f3bf30688cb25b6ae4fac4cdcb18469042fbbf32 HEAD; then  #Wine  7.20 late git 
		 if [ "$_proton_fs_hack" = "true" ]; then
			 msg2 "This version of the shared gpu patchset doesn't work with fshack"
		 fi
		_patchname='sharedgpures-driver.patch' && _patchmsg="Applied shared resources driver patchset" && nonuser_patcher
		if git merge-base --is-ancestor c65bfc062bfe1e2256a814ec7a0286214da04b0e HEAD; then
			_patchname='sharedgpures-textures.patch' && _patchmsg="Applied shared texture resources support patchset" && nonuser_patcher
			_patchname='sharedgpures-fences.patch' && _patchmsg="Applied shared fences support patchset" && nonuser_patcher
		else #f3bf30688cb25b6ae4fac4cdcb18469042fbbf32
			_patchname='sharedgpures-textures-c65bfc0.patch' && _patchmsg="Applied shared texture resources support patchset" && nonuser_patcher
			_patchname='sharedgpures-fences-c65bfc0.patch' && _patchmsg="Applied shared fences support patchset" && nonuser_patcher
		fi
		if [ "$_use_staging" = "true" ]; then 
			_patchname='sharedgpures-fixup-staging.patch' && _patchmsg="Applied shared resource multimedia fixups patchset (Staging)" &&  nonuser_patcher 
		else
			_patchname='sharedgpures-fixup.patch' && _patchmsg="Applied shared resource multimedia fixups patchset" &&  nonuser_patcher
		fi
	elif [ "$_shared_gpu_resources" = "true" ] && ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor c86955d3806879fc97b127730e9fb90e232710a7 HEAD && ! git merge-base --is-ancestor a5e39c42c8f5da421220391e44e11536a1c3b28f HEAD ); then
	  if git merge-base --is-ancestor 76db4b2459920eb2e2004255e3388b069dd1d6f9 HEAD; then
	    _patchname='sharedgpures-fixup-f3bf306.patch' && _patchmsg="Applied media-related fixes affecting shared gpu resources" && nonuser_patcher
	  elif git merge-base --is-ancestor 6f8990b4318b25709cd90f6e10e8f3fdaa89c4c4 HEAD; then
	    _patchname='sharedgpures-fixup-76db4b2.patch' && _patchmsg="Applied media-related fixes affecting shared gpu resources" && nonuser_patcher
	  elif git merge-base --is-ancestor c86955d3806879fc97b127730e9fb90e232710a7 HEAD; then
	    _patchname='sharedgpures-fixup-6f8990b.patch' && _patchmsg="Applied media-related fixes affecting shared gpu resources" && nonuser_patcher
	  fi

	  if [ "$_proton_fs_hack" = "true" ]; then
	    if git merge-base --is-ancestor df8fc0b33bbd83d330e4722172af5c809bc275aa HEAD; then
	      _patchname='sharedgpures-fshack-f3bf306.patch' && _patchmsg="Applied shared gpu resources support patchset (fshack compatible version)" && nonuser_patcher
	    elif git merge-base --is-ancestor d493fab3e81af9bf7aa00658a2297d147c11e5a3 HEAD; then
	      _patchname='sharedgpures-fshack-df8fc0b.patch' && _patchmsg="Applied shared gpu resources support patchset (fshack compatible version)" && nonuser_patcher
	    elif git merge-base --is-ancestor c86955d3806879fc97b127730e9fb90e232710a7 HEAD; then
	      _patchname='sharedgpures-fshack-d493fab.patch' && _patchmsg="Applied shared gpu resources support patchset (fshack compatible version)" && nonuser_patcher
	    fi
	  else
	    if git merge-base --is-ancestor df8fc0b33bbd83d330e4722172af5c809bc275aa HEAD; then
	      _patchname='sharedgpures-f3bf306.patch' && _patchmsg="Applied shared gpu resources support patchset" && nonuser_patcher
	    elif git merge-base --is-ancestor e553be7e776282fea77b8b60304298d9de90bd8b HEAD; then
	      _patchname='sharedgpures-df8fc0b.patch' && _patchmsg="Applied shared gpu resources support patchset" && nonuser_patcher
	      # No patches for rest intermediate commits from the same group: 19326ff94ce937e5373ab2eb8e07e0e9600ef72b ab747c6e99336f1249fdea3fdf720ca310fd550a 9a7a2ab2d9f8cfebc57ad7cbffce54c245a4c538 59d13f3d358f0f3c5695c9528fed3e051b2fc8ef a6dc349aad6abe190b68bdf79c4cca067e054407
	    elif git merge-base --is-ancestor 395061e3675be486698d7bc6e20dcd9548b837b4 HEAD; then
	      _patchname='sharedgpures-e553be7.patch' && _patchmsg="Applied shared gpu resources support patchset" && nonuser_patcher
	    elif git merge-base --is-ancestor d493fab3e81af9bf7aa00658a2297d147c11e5a3 HEAD; then
	      _patchname='sharedgpures-395061e.patch' && _patchmsg="Applied shared gpu resources support patchset" && nonuser_patcher
	    elif git merge-base --is-ancestor c86955d3806879fc97b127730e9fb90e232710a7 HEAD; then
	      _patchname='sharedgpures-d493fab.patch' && _patchmsg="Applied shared gpu resources support patchset" && nonuser_patcher
	    fi
	  fi

	fi
