#!/bin/bash

	# Shared gpu resources support
	if [ "$_shared_gpu_resources" = "true" ] && git merge-base --is-ancestor c86955d3806879fc97b127730e9fb90e232710a7 HEAD; then

	  # Shared texture resources for d3d9 and d3d11 - https://github.com/doitsujin/dxvk/pull/2516
	  if git merge-base --is-ancestor c86955d3806879fc97b127730e9fb90e232710a7 HEAD; then
	    _patchname='sharedgpures-texture.patch' && _patchmsg="Applied shared texture resources support patchset" && nonuser_patcher
	  fi
	  if git merge-base --is-ancestor c86955d3806879fc97b127730e9fb90e232710a7 HEAD; then
	    _patchname='sharedgpures-fixup.patch' && nonuser_patcher
	  fi

	  # ID3D11Fence and ID3D12Fence sharing - https://github.com/doitsujin/dxvk/pull/2608 https://github.com/HansKristian-Work/vkd3d-proton/pull/1175
	  if [ "$_proton_fs_hack" = "true" ] && git merge-base --is-ancestor c86955d3806879fc97b127730e9fb90e232710a7 HEAD; then
	    if git merge-base --is-ancestor c86955d3806879fc97b127730e9fb90e232710a7 HEAD; then
	      _patchname='sharedgpures-fences-fshack.patch' && _patchmsg="Applied shared fences support patchset (fshack compatible version)" && nonuser_patcher
	    fi
	  else
	    if git merge-base --is-ancestor c86955d3806879fc97b127730e9fb90e232710a7 HEAD; then
	      _patchname='sharedgpures-fences.patch' && _patchmsg="Applied shared fences support patchset" && nonuser_patcher
	    fi
	  fi

	fi
