#!/bin/bash

	        if [[ ! ${_staging_userargs[*]} =~ "ntdll-Syscall_Emulation" ]] && ( cd "${srcdir}"/"${_winesrcdir}" && ! git merge-base --is-ancestor 0c249e6125fc9dc6ee86b4ef6ae0d9fa2fc6291b HEAD ); then
	          if ( cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor 805f2e9252de5b4de115335f803db4e753f66ff2 HEAD ); then
	            _patchname='proton-seccomp-envvar.patch' && _patchmsg="Add WINESECCOMP env var support" && nonuser_patcher
	          elif ( cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor 595f2f9860adafed612737529745ad24c50acdb9 HEAD ); then
	            _patchname='proton-seccomp-envvar-805f2e9.patch' && _patchmsg="Add WINESECCOMP env var support" && nonuser_patcher
	          fi
	        fi
