#!/bin/bash

# https://github.com/ValveSoftware/Proton/issues/4322#issuecomment-941632443 - 2c01333d03153a2d3cc2622fa18a9ad323dd9edb 7b17d7081512db52ef852705445762ac4016c29f
if [ "$_protonify" = "true" ] && ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 7b17d7081512db52ef852705445762ac4016c29f HEAD && ! git merge-base --is-ancestor 7c046c7afd4253daa9cd8dbb6b2f466f128fecc9 HEAD ); then
  warning "Hotfix: Fix for memset performance regression"
  _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/memset/memset)
fi
