#!/bin/bash

# DXGIGetDebugInterface1 TRACE try to read values memory address of parameters, but those are not always memory addresses.
if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 08cccb522f19b3dc5b397f7c1c519604b601cee0 HEAD); then
  warning "Hotfix: Remove a TRACE in the DXGIGetDebugInterface1 stub causing segfaults."
  if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor a608ef1f2d9db962bcf2f47bc026144c0148ed41 HEAD); then
    _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/08cccb5/a608ef1)
  else
    _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/08cccb5/08cccb5)
  fi
fi
