#!/bin/bash

	# USVFS (Mod Organizer 2's virtual filesystem) patch
	if [ "$_usvfs_fix" = "true" ] && ! git merge-base --is-ancestor ee266aba74809b0fb4833f2d2762d3c687be4dd0 HEAD; then
	  _patchname='usvfs.patch' && _patchmsg="Applied USVFS (Mod Organizer 2's virtual filesystem) patch" && nonuser_patcher
	fi
