#!/bin/bash

	## CONTAINER FIXES

	# Restore heap.h header
	_committorevert=2941e58d7d6e630e88b6e9539414f1d86736c7aa && nonuser_reverter && echo -e "( Restore heap.h header file )\n" >> "$_where"/last_build_config.log

	# Temp fix for mainline-based proton builds using the valve container path
	# It depends on the install-sh approach which was deprecated with Wine 10.17-devel
	## ab3dcadb broke the simple revert. Since building upstream against proton's toolset is a huge PITA, we'll need another approach or drop it altogether
	if [ "$_no_container" = "false" ] && [[ "$_custom_wine_source" != *"ValveSoftware"* ]] && git merge-base --is-ancestor db2e157c68d5b1ced965e2ac90ecb9f3767e60fd HEAD && ! git merge-base --is-ancestor ab3dcadb4c34947bf90352f9a8efb3a9af179c0d HEAD; then
	  _committorevert=db2e157c68d5b1ced965e2ac90ecb9f3767e60fd && nonuser_reverter
	  echo -e "( Restore previous install approach for mainline-based proton )\n" >> "$_where"/last_build_config.log
	fi

	## /CONTAINER FIXES

	if [ "$_mtga_fix" = "true" ] && git merge-base --is-ancestor e5a9c256ce08868f65ed730c00cf016a97369ce3 HEAD && ! git merge-base --is-ancestor 0c249e6125fc9dc6ee86b4ef6ae0d9fa2fc6291b HEAD; then
	  _committorevert=341068aa61a71afecb712feda9aabb3dc1c3ab5f && nonuser_reverter
	  _committorevert=e5a9c256ce08868f65ed730c00cf016a97369ce3 && nonuser_reverter
	  echo -e "( MTGA bandaid reverts applied )\n" >> "$_where"/last_build_config.log
	fi

	if [ "$_sdl_joy_support" = "true" ] && [ "$_use_staging" != "true" ] && [ "$_EXTERNAL_INSTALL" = "proton" ] && git merge-base --is-ancestor e4fbae832c868e9fcf5a91c58255fe3f4ea1cb30 HEAD && ! git merge-base --is-ancestor a17367291104e46c573b7213ee94a0f537563ace HEAD; then
	  _committorevert=e4fbae832c868e9fcf5a91c58255fe3f4ea1cb30 && nonuser_reverter
	  echo -e "( Proton SDL Joystick support unbreak revert applied )\n" >> "$_where"/last_build_config.log
	fi
	if [ "$_gamepad_additions" = "true" ] && [ "$_use_staging" = "true" ] && [ "$_EXTERNAL_INSTALL" = "proton" ] && git merge-base --is-ancestor da7d60bf97fb8726828e57f852e8963aacde21e9 HEAD && ! git merge-base --is-ancestor 6373792eec0f122295723cae77b0115e6c96c3e4 HEAD; then
	  _committorevert=da7d60bf97fb8726828e57f852e8963aacde21e9 && nonuser_reverter
	  echo -e "( Proton gamepad additions unbreak revert applied )\n" >> "$_where"/last_build_config.log
	fi

	if [ "$_warframelauncher_fix" = "true" ] && git merge-base --is-ancestor 5e218fe758fe6beed5c7ad73405eccf33c307e6d HEAD && ! git merge-base --is-ancestor adfb042819472a23f4d07f7aeea194e463855806 HEAD; then
	  _committorevert=bae4776c571cf975be1689594f4caf93ad23e0ca && nonuser_reverter
	  _committorevert=5e218fe758fe6beed5c7ad73405eccf33c307e6d && nonuser_reverter
	  echo -e "( Warframe Launcher unbreak reverts applied )\n" >> "$_where"/last_build_config.log
	fi

	if [ "$_proton_fs_hack" = "true" ]; then
	  if ! git merge-base --is-ancestor aee91dc4ac08428e74fbd21f97438db38f84dbe5 HEAD; then
	    _committorevert=427152ec7b4ee85631617b693dbf1deea763c0ba && nonuser_reverter
	    _committorevert=b7b4bacaf99661e07c2f07a0260680b4e8bed4f8 && nonuser_reverter
	    _committorevert=acf03ed9da0f7d3f94de9b47c44366be3ee47f8e && nonuser_reverter
	    _committorevert=914b5519b1cd96f9ae19f1eec226e94af96354b9 && nonuser_reverter
	    _committorevert=99d047724e768822d6508573cd82a5c75b30bdcb && nonuser_reverter
	    _committorevert=413aad39135b0b0f8255500b85fcc05337a5f138 && nonuser_reverter
	    _committorevert=9ae8da6bb4a8f66d55975fa0f14e5e413756d324 && nonuser_reverter
	    _committorevert=de94cfa775f9f41d1d65cbd8e7bf861cd7f9a871 && nonuser_reverter
	    _committorevert=6dbb153ede48e77a87dddf37e5276276a701c5c3 && nonuser_reverter
	    _committorevert=81f8b6e8c215dc04a19438e4369fcba8f7f4f333 && nonuser_reverter
	    echo -e "( FS hack unbreak reverts applied )\n" >> "$_where"/last_build_config.log
	  elif git merge-base --is-ancestor 2538b0100fbbe1223e7c18a52bade5cfe5f8d3e3 HEAD && ! git merge-base --is-ancestor 0f972e2247932f255f131792724e4796b4b2b87a HEAD; then
	    _committorevert=16984895f0191dad12d55dee422214645b51aece && nonuser_reverter
	    _committorevert=0120a1aa40936fc6d57d83eb12709b951c7b88d6 && nonuser_reverter
	    _committorevert=4a330b29212402b9700828be82939112bd11a786 && nonuser_reverter
	    _committorevert=bbae35f0fb04ea7efb8e1d6e5535e42715ae7766 && nonuser_reverter
	    _committorevert=ec245c7e300f7cb779cf404079872f68c812585e && nonuser_reverter
	    _committorevert=586f68f414924b1e41fec10a72b1aacced068885 && nonuser_reverter
	    _committorevert=d9625e5a01a52496d1fb7f1a9a691fd3ec8332db && nonuser_reverter
	    _committorevert=715a04daabdab616b530ef5a937827df7c2523c3 && nonuser_reverter
	    _committorevert=f04360cfbec574dc37675df141ef8fc14e1302ba && nonuser_reverter
	    _committorevert=1aa7c9af90c340f45e03c6b94525704ad19eb657 && nonuser_reverter
	    _committorevert=fd29fe4ea73d87e39bd3d0ddd791c14f536508b7 && nonuser_reverter
	    _committorevert=2b484b1ac7a5510be54cb5341143d89dc1924b37 && nonuser_reverter
	    _committorevert=440fab3870b3c9ea778031ec51db69f8c3a687f5 && nonuser_reverter
	    _committorevert=b45c04f4c352ef81df5312684008839f4eeee03d && nonuser_reverter
	    _committorevert=9c99d9bceba34559a32f1e5906a6fcbcf91b0004 && nonuser_reverter
	    _committorevert=2116b49717f26802b51e2904de8d74651da33545 && nonuser_reverter
	    _committorevert=5491e939bc22f0ab479aec6b8a525be9c5ff5e35 && nonuser_reverter
	    _committorevert=d13b61b7385a6a380fb91720c511b194926fa0ca && nonuser_reverter
	    _committorevert=4a2481631331e2743476ea4e1b0005f8f5024242 && nonuser_reverter
	    _committorevert=0d42388095e4fd5c7702a61824b01ce0f9fc4d74 && nonuser_reverter
	    _committorevert=7dd52f6d24f372f08ab71f0acbb0a2b028d390ba && nonuser_reverter
	    _committorevert=9905a5a81d6baf59e992c5b2a8ea92ee4054e5d6 && nonuser_reverter
	    _committorevert=45d991d54138523e5278db5618eb458100982294 && nonuser_reverter
	    _committorevert=f5e6c086f91749e9e302c1abf858807535bc9775 && nonuser_reverter
	    _committorevert=a8b4cf7f2d3d1fbd79308a106a84e753cdac69e8 && nonuser_reverter
	    _committorevert=2a6de8d7f7d6f5ac018d8e330cfa580fc0c3b9e5 && nonuser_reverter
	    _committorevert=6f305dd881e16f77f9eb183684d04b0b8746b769 && nonuser_reverter
	    _committorevert=679ff720902b8e5d5d750b980084bdcdc9a051ed && nonuser_reverter
	    _committorevert=0b0ac41981006514616abdd4c4b6922cf66be7b6 && nonuser_reverter
	    _committorevert=dd13b274104b561f05873e8acdc4bfd34bbe796e && nonuser_reverter
	    _committorevert=3a3c7cbd209e23cc6ee88299b3ba877ab20a767f && nonuser_reverter
	    _committorevert=6f9d20806e821ab07c8adf81ae6630fae94b00ef && nonuser_reverter
	    _committorevert=145cfce1135a7e59cc4c89cd05b572403f188161 && nonuser_reverter
	    _committorevert=e3eb89d5ebb759e975698b97ed8b547a9de3853f && nonuser_reverter
	    _committorevert=707fcb99a60015fcbb20c83e9031bc5be7a58618 && nonuser_reverter
	    _committorevert=8cd6245b7633abccd68f73928544ae4de6f76d52 && nonuser_reverter
	    _committorevert=26b26a2e0efcb776e7b0115f15580d2507b10400 && nonuser_reverter
	    _committorevert=fd6f50c0d3e96947846ca82ed0c9bd79fd8e5b80 && nonuser_reverter
	    _committorevert=2538b0100fbbe1223e7c18a52bade5cfe5f8d3e3 && nonuser_reverter
	    echo -e "( FS hack unbreak reverts applied )\n" >> "$_where"/last_build_config.log
	  fi
	fi

	if [ "$_proton_rawinput" = "true" ] && [ "$_proton_fs_hack" = "true" ] && [ "$_use_staging" = "true" ] && ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 26c1131201f8fd9918a01231a7eb6f1989400858 HEAD ) && ( cd "${srcdir}"/"${_stgsrcdir}" && ! git merge-base --is-ancestor 82cff8bbdbc133cc14cdb9befc36c61c3e49c242 HEAD ); then
	  _committorevert=306c40e67319cae8e4c448ec8fc8d3996f87943f && nonuser_reverter
	  _committorevert=26c1131201f8fd9918a01231a7eb6f1989400858 && nonuser_reverter
	  echo -e "( Proton rawinput unbreak reverts applied )\n" >> "$_where"/last_build_config.log
	fi

	# Kernelbase reverts patchset - cleanly reverting part
	if [ "$_kernelbase_reverts" = "true" ] || [ "$_EXTERNAL_INSTALL" = "proton" ] && [ "$_unfrog" != "true" ] && ! git merge-base --is-ancestor b7db0b52cee65a008f503ce727befcad3ba8d28a HEAD; then
	  _committorevert=b0199ea2fe8f9b77aee7ab4f68c9ae1755442586 && nonuser_reverter
	  _committorevert=608d086f1b1bb7168e9322c65224c23f34e75f29 && nonuser_reverter
	  _committorevert=b7db0b52cee65a008f503ce727befcad3ba8d28a && nonuser_reverter
	  _committorevert=3ede217e5cd80b18f709339aea281356579756cb && nonuser_reverter
	  _committorevert=87307de2173ee813daca9bd93ec750f17d3eda94 && nonuser_reverter
	  if [ "$_use_staging" != "true" ]; then
	    _committorevert=3dadd980bfbb2fb05a1a695decd06a429ddda97c && nonuser_reverter
	  fi
	  _committorevert=e5354008f46bc0e345c06ac06a7a7780faa9398b && nonuser_reverter
	  _committorevert=461b5e56f95eb095d97e4af1cb1c5fd64bb2862a && nonuser_reverter
	  echo -e "( Kernelbase reverts clean reverts applied )\n" >> "$_where"/last_build_config.log
	fi

	# GetPackagesByPackageFamily(), PackageFullNameFromId(), GetPackagePath() implemented through protonify
	if [ "$_protonify" = "true" ]; then
	  _committorevert=240556e2b8cb94fc9cc85949b7e043f392b1802a && nonuser_reverter # GetPackagePathByFullName
	  _committorevert=bd89ab3040e30c11b34a95072d88f635ade03bdc && nonuser_reverter
	fi
