#!/bin/bash

	# Bypass compositor in fullscreen mode - Reduces stuttering and improves performance
	if [ "$_proton_fs_hack" = "true" ] && [ "$_FS_bypass_compositor" = "true" ] && [ "$_FS_bypass_compositor_legacy" != "false" ]; then
	  _patchname='FS_bypass_compositor.patch' && _patchmsg="Applied Fullscreen compositor bypass patch" && nonuser_patcher
	fi
