#!/bin/bash

	# Legacy Proton Fullscreen inline patching
	if [ "$_unfrog" != "true" ] && [ "$_proton_rawinput" = "true" ] && [ "$_proton_fs_hack" = "true" ] && [ "$_use_staging" = "true" ] && ( cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor 938dddf7df920396ac3b30a44768c1582d0c144f HEAD ); then
	  echo -e "\nLegacy Proton Fullscreen inline patching" >> "$_where"/prepare.log
	  for _f in "$_where"/valve_proton_fullscreen_hack-staging-{938dddf,de64501,82c6ec3,7cc69d7,0cb79db,a4b9460,57bb5cc,6e87235}.patch; do
	    patch "${_f}" >> "$_where"/prepare.log << 'EOM'
@@ -2577,7 +2577,7 @@ index 1209a250b0..077c18ac10 100644
 +    input.u.mi.dx = pt.x;
 +    input.u.mi.dy = pt.y;
 +
-     TRACE( "pos %d,%d (event %f,%f, accum %f,%f)\n", input.u.mi.dx, input.u.mi.dy, dx, dy, x_rel->accum, y_rel->accum );
+     TRACE( "pos %d,%d (event %f,%f)\n", input.u.mi.dx, input.u.mi.dy, dx, dy );

      input.type = INPUT_MOUSE;
 diff --git a/dlls/winex11.drv/opengl.c b/dlls/winex11.drv/opengl.c
EOM
      done
	fi

	# Proton Fullscreen patch - Allows resolution changes for fullscreen games without changing desktop resolution
	if [ "$_proton_fs_hack" = "true" ] && [ "$_unfrog" != "true" ]; then
	  if [ "$_FS_bypass_compositor" != "true" ] && [ "$_FS_bypass_compositor_legacy" != "false" ]; then
	    _patchname='FS_bypass_compositor.patch' && _patchmsg="Applied Fullscreen compositor bypass patch" && nonuser_patcher
	  fi
	  if [ "$_use_staging" = "true" ]; then
	    if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 78ecbc4b2d548e4cb57af622d40d0149366a7354 HEAD ); then
	      _patchname='valve_proton_fullscreen_hack-staging.patch' && _patchmsg="Applied Proton fullscreen hack patch (staging)" && nonuser_patcher
	    else
	      if git merge-base --is-ancestor a831aa1875e6a3cc6eb3d64a127c45ebb9c1ce60 HEAD; then
	        _lastcommit="78ecbc4"
	      elif git merge-base --is-ancestor 8a8b5179d0c59d7c4171ad5447ef55689cba86b3 HEAD; then
	        _lastcommit="a831aa1"
	      elif git merge-base --is-ancestor 656edbb508d51cbe3155d856ee3f2c27a6cd4cba HEAD; then
	        _lastcommit="8a8b517"
	      elif git merge-base --is-ancestor 656edbb508d51cbe3155d856ee3f2c27a6cd4cba HEAD; then
	        _lastcommit="439fb25"
	      elif git merge-base --is-ancestor 548bc54bf396d74b5b928bf9be835272ddda1886 HEAD; then
	        _lastcommit="656edbb"
	      elif git merge-base --is-ancestor 1c1fe30cc50da2b0596096b04b75d8c1e598f8e7 HEAD; then
	        _lastcommit="548bc54"
	      elif git merge-base --is-ancestor d1290b6ec7b1f1d0a18742f4da939a8839f55857 HEAD; then
	        _lastcommit="1c1fe30"
	      elif ( cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor c9c7130f3cc51c1861a5ef3e703fd442e8942ba4 HEAD ); then
	        _lastcommit="d1290b6"
	      elif git merge-base --is-ancestor a7ec245f844762cce6fb789fe3ffb1bf42d44249 HEAD; then
	        _lastcommit="c9c7130"
	      elif git merge-base --is-ancestor f46c4a3920ce8e96b37b606c207add7f596f1950 HEAD; then
	        _lastcommit="a7ec245"
	      elif git merge-base --is-ancestor 8285f616030f27877922ff414530d4f909306ace HEAD; then
	        _lastcommit="f46c4a3"
	      elif git merge-base --is-ancestor 211da181c9140541ab7f7fcfa479367b3f7783eb HEAD; then
	        _lastcommit="8285f61"
	      elif git merge-base --is-ancestor 9561af9a7d8d77e2f98341e278c842226cae47ed HEAD; then
	        _lastcommit="211da18"
	      elif ( cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor a71e4cdf85fae1282d7cab042fabd66e407d11d6 HEAD ); then
	        _lastcommit="9561af9"
	      elif git merge-base --is-ancestor 454712a94d62849324d20014c786b0e7c452bf61 HEAD; then
	        _lastcommit="a71e4cd"
	      elif git merge-base --is-ancestor a92ab08688b1e425c887ccb77196bbf681f24be1 HEAD; then
	        _lastcommit="454712a"
	      elif ( cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor 7f18df46333b5686f2e3622ebc474530e15c6888 HEAD ); then
	        _lastcommit="a92ab08"
	      elif git merge-base --is-ancestor 011fabb2c43d13402ea18b6ea7be3669b5e6c7a8 HEAD; then
	        _lastcommit="7f18df4"
	      elif git merge-base --is-ancestor 6d04e6c3a9c4c8b1cc2d1ba337c33cc56d1a8ab2 HEAD; then
	        _lastcommit="011fabb"
	      elif git merge-base --is-ancestor 62cb6ace2cfe46358e6526868145a5bd8a7f990b HEAD; then
	        _lastcommit="6d04e6c"
	      elif git merge-base --is-ancestor a27d5bae114eef5352b699ee38975bc8793b4dcb HEAD; then
	        _lastcommit="62cb6ac"
	      elif git merge-base --is-ancestor a24bdfc2c69c5648cbb3df762149b2647e209a09 HEAD; then
	        _lastcommit="a27d5ba"
	      elif git merge-base --is-ancestor 0f972e2247932f255f131792724e4796b4b2b87a HEAD; then
	        _lastcommit="a24bdfc"
	      elif git merge-base --is-ancestor 1e074c39f635c585595e9f3ece99aa290a7f9cf8 HEAD; then
	        _lastcommit="0f972e2"
	      elif git merge-base --is-ancestor 1e074c39f635c585595e9f3ece99aa290a7f9cf8 HEAD; then
	        _lastcommit="af3d292"
	      elif git merge-base --is-ancestor 314cd9cdd542db658ce7a01ef0a7621fc2d9d335 HEAD; then
	        _lastcommit="1e074c3"
	      elif git merge-base --is-ancestor 5dd03cbc8f5cc8fa349d1ce0f155139094eff56c HEAD; then
	        _lastcommit="314cd9c"
	      elif git merge-base --is-ancestor 408a5a86ec30e293bf9e6eec4890d552073a82e8 HEAD; then
	        _lastcommit="5dd03cb"
	      elif git merge-base --is-ancestor 3db619d46e70a398a06001573fb42b0a32d81209 HEAD; then
	        _lastcommit="408a5a8"
	      elif git merge-base --is-ancestor 707fcb99a60015fcbb20c83e9031bc5be7a58618 HEAD; then
	        _lastcommit="3db619d"
	      elif git merge-base --is-ancestor b0e2d046fc69cc4a4c5aefe383793950b44a1a7b HEAD; then
	        _lastcommit="707fcb9"
	      elif git merge-base --is-ancestor 594814c00ab059d9686ed836b1865f8a94859c8a HEAD; then
	        _lastcommit="b0e2d04"
	      elif git merge-base --is-ancestor 086c686e817a596e35c41dd5b37f3c28587af9d5 HEAD; then
	        _lastcommit="594814c"
	      elif git merge-base --is-ancestor 74dc0c5df9c3094352caedda8ebe14ed2dfd615e HEAD; then
	        _lastcommit="086c686"
	      elif git merge-base --is-ancestor aee91dc4ac08428e74fbd21f97438db38f84dbe5 HEAD; then
	        _lastcommit="74dc0c5"
	      elif git merge-base --is-ancestor 7e736b5903d3d078bbf7bb6a509536a942f6b9a0 HEAD; then
	        _lastcommit="aee91dc"
	      elif ( cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor 734918298c4a6eb1cb23f31e21481f2ef58a0970 HEAD ); then
	        _lastcommit="7e736b5"
	      elif git merge-base --is-ancestor de6450135de419ac7e64aee0c0efa27b60bea3e8 HEAD; then
	        _lastcommit="938dddf"
	      elif git merge-base --is-ancestor 82c6ec3a32f44e8b3e0cc88b7f10e0c0d7fa1b89 HEAD; then
	        _lastcommit="de64501"
	      elif ( cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor 7cc69d770780b8fb60fb249e007f1a777a03e51a HEAD ); then
	        _lastcommit="82c6ec3"
	      elif git merge-base --is-ancestor 0cb79db12ac7c48477518dcff269ccc5d6b745e0 HEAD; then
	        _lastcommit="7cc69d7"
	      elif git merge-base --is-ancestor a4b9460ad68bad6675f9e50b390503db9ef94d6b HEAD; then
	        _lastcommit="0cb79db"
	      elif git merge-base --is-ancestor 57bb5cce75aed1cb06172cc0b6b696dfb008e7c1 HEAD; then
	        _lastcommit="a4b9460"
	      elif git merge-base --is-ancestor 6e87235523f48d523285409dcbbd7885df9948d0 HEAD; then
	        _lastcommit="57bb5cc"
	      else
	        _lastcommit="6e87235"
          fi
	      _patchname="valve_proton_fullscreen_hack-staging-$_lastcommit.patch" && _patchmsg="Applied Proton fullscreen hack patch ($_lastcommit)" && nonuser_patcher
	    fi
	  else
	    if git merge-base --is-ancestor af3d292343034b87403b1c8738e29bd3479fe87e HEAD; then
	      _patchname='valve_proton_fullscreen_hack.patch' && _patchmsg="Applied Proton fullscreen hack patch (mainline)" && nonuser_patcher
	    elif git merge-base --is-ancestor 1e074c39f635c585595e9f3ece99aa290a7f9cf8 HEAD; then
	      _patchname='valve_proton_fullscreen_hack-af3d292.patch' && _patchmsg="Applied Proton fullscreen hack patch (mainline)" && nonuser_patcher
	    elif git merge-base --is-ancestor 314cd9cdd542db658ce7a01ef0a7621fc2d9d335 HEAD; then
	      _patchname='valve_proton_fullscreen_hack-1e074c3.patch' && _patchmsg="Applied Proton fullscreen hack patch (mainline)" && nonuser_patcher
	    elif git merge-base --is-ancestor 5dd03cbc8f5cc8fa349d1ce0f155139094eff56c HEAD; then
	      _patchname='valve_proton_fullscreen_hack-314cd9c.patch' && _patchmsg="Applied Proton fullscreen hack patch (mainline)" && nonuser_patcher
	    elif git merge-base --is-ancestor 408a5a86ec30e293bf9e6eec4890d552073a82e8 HEAD; then
	      _patchname='valve_proton_fullscreen_hack-5dd03cb.patch' && _patchmsg="Applied Proton fullscreen hack patch (mainline)" && nonuser_patcher
	    elif git merge-base --is-ancestor 3db619d46e70a398a06001573fb42b0a32d81209 HEAD; then
	      _patchname='valve_proton_fullscreen_hack-408a5a8.patch' && _patchmsg="Applied Proton fullscreen hack patch (mainline)" && nonuser_patcher
	    elif git merge-base --is-ancestor 707fcb99a60015fcbb20c83e9031bc5be7a58618 HEAD; then
	      _patchname='valve_proton_fullscreen_hack-3db619d.patch' && _patchmsg="Applied Proton fullscreen hack patch (mainline)" && nonuser_patcher
	    elif git merge-base --is-ancestor b0e2d046fc69cc4a4c5aefe383793950b44a1a7b HEAD; then
	      _patchname='valve_proton_fullscreen_hack-707fcb9.patch' && _patchmsg="Applied Proton fullscreen hack patch (mainline)" && nonuser_patcher
	    elif git merge-base --is-ancestor 594814c00ab059d9686ed836b1865f8a94859c8a HEAD; then
	      _patchname='valve_proton_fullscreen_hack-b0e2d04.patch' && _patchmsg="Applied Proton fullscreen hack patch (mainline)" && nonuser_patcher
	    elif git merge-base --is-ancestor 086c686e817a596e35c41dd5b37f3c28587af9d5 HEAD; then
	      _patchname='valve_proton_fullscreen_hack-594814c.patch' && _patchmsg="Applied Proton fullscreen hack patch (mainline)" && nonuser_patcher
	    elif git merge-base --is-ancestor 74dc0c5df9c3094352caedda8ebe14ed2dfd615e HEAD; then
	      _patchname='valve_proton_fullscreen_hack-086c686.patch' && _patchmsg="Applied Proton fullscreen hack patch (mainline <086c686)" && nonuser_patcher
	    elif git merge-base --is-ancestor aee91dc4ac08428e74fbd21f97438db38f84dbe5 HEAD; then
	      _patchname='valve_proton_fullscreen_hack-74dc0c5.patch' && _patchmsg="Applied Proton fullscreen hack patch (mainline <74dc0c5)" && nonuser_patcher
	    else
	      _proton_fs_hack="false"
	    fi
	  fi
	  if [ "$_FS_bypass_compositor" != "true" ] && [ "$_FS_bypass_compositor_legacy" != "false" ]; then
	    _FS_bypass_compositor="true"
	    _patchname='FS_bypass_compositor-disabler.patch' && _patchmsg="Turned off Fullscreen compositor bypass" && nonuser_patcher
	  fi
	  # Legacy split realmodes patchset
	  if ( cd "${srcdir}"/"${_stgsrcdir}" && ! git merge-base --is-ancestor 734918298c4a6eb1cb23f31e21481f2ef58a0970 HEAD ); then
	    _patchname='valve_proton_fullscreen_hack_realmodes.patch' && _patchmsg="Using real modes in FS hack addon" && nonuser_patcher
	  fi
	fi
