#!/bin/bash

# Protonify the staging syscall emu patchset
if [ "$_use_staging" = "true" ] && ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 4de079bb7247c8b849558c0f27a280a9546c5570 HEAD ); then
  if ( cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor 66c0fdc1590e00ce471a6c55f4d97ededd1f5aae HEAD ); then
    warning "Hotfix: Protonify staging syscall emu"
    if ( cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor 9937bf04635e33efa0d32e6e5af3a2bb55ad8f9c HEAD ); then
      _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/syscall_emu/protonify_stg_syscall_emu-009)
    elif ( cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor 0ee2ac8499bbde23ad14bb0ffe125016faccd301 HEAD ); then
      _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/syscall_emu/protonify_stg_syscall_emu-008)
    elif ( cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor feb91195ff12074276ea3b83047d4c8f2c70d738 HEAD ); then
      _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/syscall_emu/protonify_stg_syscall_emu-007)
    elif ( cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor 24319dc308046ed520dd2cb92f57d54f96ebec21 HEAD ); then
      _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/syscall_emu/protonify_stg_syscall_emu-006)
    else
      _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/syscall_emu/protonify_stg_syscall_emu-005)
    fi
    # The rdr2 patch needs to be applied before the quake champions patch, so let's inject into $_where dir with a check in prepare script
    ln -s "$_where"/wine-tkg-patches/hotfixes/syscall_emu/rdr2.patch "$_where"/rdr2.patch
    ln -s "$_where"/wine-tkg-patches/hotfixes/syscall_emu/rdr2.patch "$srcdir"/rdr2.patch
  elif ( cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor 6f3825b11f8444e87ff203f305debab81858f97d HEAD ); then
    warning "Hotfix: Protonify staging syscall emu"
    _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/syscall_emu/protonify_stg_syscall_emu-004)
    # Along with rdr2 patch, we need the ntdll-Syscall_Emulation patchset re-enabled for the quake champions fix
    _quake_champions_fix="false"
  elif ( cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor 876024f44fde737fcf43e8b0cb8e75575e65d449 HEAD ); then
    warning "Hotfix: Protonify staging syscall emu"
    _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/syscall_emu/protonify_stg_syscall_emu-003)
  elif ( cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor e3cca687befffb4baee144dcd55f01a3204176eb HEAD ); then
    warning "Hotfix: Protonify staging syscall emu"
    _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/syscall_emu/protonify_stg_syscall_emu-002)
  else
    warning "Hotfix: Protonify staging syscall emu"
    _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/syscall_emu/protonify_stg_syscall_emu-001)
  fi
fi
