#!/bin/bash

# WINEDEBUG crash - legacy
if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor ca13f489e18fb1f7944e3bdcfdfc4a810bf80994 HEAD ) && ( cd "${srcdir}"/"${_stgsrcdir}" && ! git merge-base --is-ancestor a1bda115af8ad3484b7c17eac7da74e4906fa9e4 HEAD ); then
  if [ "$_hotfixes_no_confirm" != "true" ] && [ "$_hotfixes_no_confirm" != "ignore" ]; then
    warning "Hotfix: Upstream commits cd215bb to ca13f48 are interacting badly with WINEDEBUG env var and break staging."
    read -rp "Are you okay to revert them ?"$'\n> N/y : ' _hotfixansw;
  fi
  if [[ "$_hotfixansw" =~ [yY] ]] || [ "$_hotfixes_no_confirm" = "true" ]; then
    _hotfix_mainlinereverts=(cd215bb49bc240cdce5415c80264f8daa557636a 8ca9e0b1abba7640e288df7b55b60903bc52fc9d 6a1667fab428764eeaba38ac9b5cb1813c5cffda 9b12068c6c8ba656e8ca768227b1a970877d4730 cc5953048e570155deb791b9e9e738a0508c2032 0936606c383744daa8be046db72e8e888522ce21 ca13f489e18fb1f7944e3bdcfdfc4a810bf80994)
    _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/a1bda115/acd209d6039f2492bdc8aca3d15bb1b268b04f1a)
    # Staging conflict
    if ( cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor 4501d49149e37b37edd61f8a1694930db7418a61 HEAD ); then
      _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/a1bda115/4501d49149e37b37edd61f8a1694930db7418a61)
    fi
  fi
fi
