#!/bin/bash

	# CSMT toggle patch - Corrects the CSMT toggle to be more logical
	if [ "$_CSMT_toggle" = "true" ] && [ "$_use_staging" = "true" ]; then
	  cd "${srcdir}"/"${_stgsrcdir}"
	  if git merge-base --is-ancestor c1b4af92f74d7bd330003d39d0bb1f966fdb70a9 HEAD; then
	    _patchname='CSMT-toggle.patch' && _patchmsg="Applied CSMT toggle logic patch" && nonuser_patcher
	  elif git merge-base --is-ancestor ef11bb63ce54490bc5a1e14ab650207b515340da HEAD; then
	    _patchname='CSMT-toggle-c1b4af9.patch' && _patchmsg="Applied CSMT toggle logic patch" && nonuser_patcher
	  elif git merge-base --is-ancestor 5e685d6df972b658fba296dafb5db189af73c7d5 HEAD; then
	    _patchname='CSMT-toggle-ef11bb6.patch' && _patchmsg="Applied CSMT toggle logic patch" && nonuser_patcher
	  else
	    _patchname='CSMT-toggle-5e685d6.patch' && _patchmsg="Applied CSMT toggle logic patch" && nonuser_patcher
	  fi
	  cd "${srcdir}"/"${_winesrcdir}"
	fi
