#!/bin/bash

# Battle.net got broken by 414b31bc0bbbfe005e90a1946a649082dc303c55 - https://bugs.winehq.org/show_bug.cgi?id=51331
if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 414b31bc0bbbfe005e90a1946a649082dc303c55 HEAD && ! git merge-base --is-ancestor 026b192018e254c74c6a1f07d82637716ff48e8d HEAD ); then
  warning "Hotfix: 414b31b breaks battle.net (agent crashes) - patch by Zebediah Figura"
  _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/414b31b/zeb-fb3956f-fix)
fi
