#!/bin/bash

# Staging rawinput fixup from openglfreak
if [ "$_use_staging" = "true" ] && ( cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor c9c7130f3cc51c1861a5ef3e703fd442e8942ba4 HEAD && ! git merge-base --is-ancestor 56fd61a713174cc48a62a81b0a306acac93dd30c HEAD ); then
  _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/staging_rawinput/c9c7130-hotfix)
fi

# Staging rawinput restoration following 1295604addb472235256a847b644855693feeecd disabling it due to upstream changes
if [ "$_use_staging" = "true" ] && ( cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor 1295604addb472235256a847b644855693feeecd HEAD && ! git merge-base --is-ancestor c9c7130f3cc51c1861a5ef3e703fd442e8942ba4 HEAD ); then
  if ( [ "$_hotfixes_no_confirm" != "true" ] && [ "$_hotfixes_no_confirm" != "ignore" ] ); then
    warning "Hotfix: Staging's mouse rawinput support patchset is currently disabled"
    read -rp "  Restore it?"$'\n> N/y : ' _hotfixansw_staging_rawinput;
  fi
  if [[ "$_hotfixansw_staging_rawinput" =~ [yY] ]] || [ "$_hotfixes_no_confirm" = "true" ] && [ "$_hotfixansw_staging_rawinput" != "false" ]; then
    warning "Hotfix: Restore staging's mouse rawinput support patchset"
    _hotfix_mainlinereverts+=(f7ac9f309f2964e131c8e60c5ff3a878b67b2e32 dfa11dc040f93aceec7009eeb3a57b95764c1c64 da11387857f69d8bf68de56197390052f680f283 7bc5b6800e0a78ab744532b7ed28ee04d38110f3)
    _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/staging_rawinput/staging_rawinput_restore)
  else
    warning "Disabling proton fs hack because it depends on staging rawinput"
    _proton_fs_hack="false"
  fi
fi
