#!/bin/bash

	# Revert moving various funcs to kernelbase & ntdll to fix some dll loading issues and ntdll crashes (with Cemu and Blizzard games notably)
	if [ "$_kernelbase_reverts" = "true" ] || [ "$_EXTERNAL_INSTALL" = "proton" ] && [ "$_unfrog" != "true" ] && git merge-base --is-ancestor 8d25965e12717b266f2fc74bb10d915234d16772 HEAD && ! git merge-base --is-ancestor b7db0b52cee65a008f503ce727befcad3ba8d28a HEAD; then
	  if git merge-base --is-ancestor 461b5e56f95eb095d97e4af1cb1c5fd64bb2862a HEAD; then
	    if [ "$_use_staging" = "true" ]; then
	      _patchname='proton-tkg-staging-kernelbase-reverts.patch' && _patchmsg="Using kernelbase reverts patch (staging)" && nonuser_patcher
	    else
	      _patchname='proton-tkg-kernelbase-reverts.patch' && _patchmsg="Using kernelbase reverts patch" && nonuser_patcher
	    fi
	  else
	    if git merge-base --is-ancestor fd3735cf4dd55b5c582bd51bb03647e5eaf12847 HEAD; then
	      _lastcommit="461b5e5"
	    elif git merge-base --is-ancestor c258b5ef1100c8c238aab0a17ca743a326829aac HEAD; then
	      _lastcommit="fd3735c"
	    elif git merge-base --is-ancestor 9551cb0b84dc0c0c9c1778cc37d7bafef4fd4299 HEAD; then
	      _lastcommit="c258b5e"
	    elif git merge-base --is-ancestor 8d25965e12717b266f2fc74bb10d915234d16772 HEAD; then
	      _lastcommit="9551cb0"
	    else
	      _lastcommit="none"
	    fi
	    if [ "$_lastcommit" != "none" ]; then
	      if [ "$_use_staging" = "true" ]; then
	        _patchname="proton-tkg-staging-kernelbase-reverts-$_lastcommit.patch" && _patchmsg="Using kernelbase reverts patch (staging) (<$_lastcommit)" && nonuser_patcher
	      else
	        _patchname="proton-tkg-kernelbase-reverts-$_lastcommit.patch" && _patchmsg="Using kernelbase reverts patch (<$_lastcommit)" && nonuser_patcher
	      fi
	    fi
	  fi
	fi
