#!/bin/bash

# Disable some staging patchsets breaking CEG in Proton
if [ "$_EXTERNAL_INSTALL" = "proton" ]; then
  if ( cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor 56a387bf1d80c76e69bd9015536dbe40b22f064d HEAD ); then
    _staging_args+=(-W ntdll-Junction_Points -W server-File_Permissions -W server-Stored_ACLs)
    if ( cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor 155e98e765990f33010035bd36f039cc6fca5ecd HEAD ); then
      _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/proton_staging_CEG_support/commit-155e98e)
    elif ( cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor 24753f8756ff982ee20cbb98bda79b15c8c3d57d HEAD ); then
      _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/proton_staging_CEG_support/commit-24753f8)
    elif ( cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor 2056903cdfdc3580427edfb56f4058313c14ddf2 HEAD ); then
      _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/proton_staging_CEG_support/commit-2056903)
    elif ( cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor 7655d14b6ad54f45e93c7c03fdc311b118b7a333 HEAD ); then
      _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/proton_staging_CEG_support/commit-7655d14)
    elif ( cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor 68918863dcab756a407a58cf6b6869c21557e3d0 HEAD ); then
      _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/proton_staging_CEG_support/commit-6891886)
    else
      _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/proton_staging_CEG_support/commit-64a9d9f)
      #_hotfixes+=("$_where"/wine-tkg-patches/hotfixes/proton_staging_CEG_support/commit-ac758de)
    fi
  fi
fi
