#!/bin/bash

	# apply wine-pba patchset
	if [ "$_use_pba" = "true" ]; then
	  if [ "$_pba_version" != "none" ]; then
	    _patchname="PBA${_pba_version}.patch" && _patchmsg="Using pba (${_pba_version}) patchset" && nonuser_patcher
	  fi
	fi
