#!/bin/bash

  # Fix NosTale mouse bug (very big thanks to Morsisko, NosApki team and Linux community) - https://github.com/PSzczepanski1996/proton-ge-nostale/commit/a4078f03775d0a2cc45c7fe048893ab33fc6acfc
  if [ "$_unfrog" = "true" ]; then
    warning "Hotfix: Fix NosTale mouse bug"
    cp "$_where"/wine-tkg-patches/hotfixes/NosTale/nostale_mouse_fix_proton.mypatch "$_where"/
  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 879ef36148b489f82a3d99d2113b01eb7eb985a1 HEAD ); then
    warning "Hotfix: Fix NosTale mouse bug"
    _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/NosTale/nostale_mouse_fix)
  fi
