#!/bin/bash

  # Fix NosTale mouse bug (very big thanks to Morsisko, NosApki team and Linux community) - https://github.com/PSzczepanski1996/proton-ge-nostale/commit/a4078f03775d0a2cc45c7fe048893ab33fc6acfc
  if [ "$_unfrog" = "true" ]; then
    if [[ "$_plain_version" = *_7.0 ]]; then
      warning "Hotfix: Fix NosTale mouse bug"
      cp "$_where"/wine-tkg-patches/hotfixes/NosTale/nostale_mouse_fix_proton.mypatch "$_where"/
    fi
  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 879ef36148b489f82a3d99d2113b01eb7eb985a1 HEAD ); then
    warning "Hotfix: Fix NosTale mouse bug"
    if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 0bfdac7f6585f9bfce1d37335f53d2ed307d073b HEAD ); then
      _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/NosTale/nostale_mouse_fix)
    elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 5127bedd54716a773fe079e19a4e38891b939671 HEAD ); then
      _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/NosTale/nostale_mouse_fix-0bfdac7)
    else
      _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/NosTale/nostale_mouse_fix-5127bed)
    fi
  fi
