#!/bin/bash

	# Enable new dynamic WINEARCH=wow64 by default
	if [ "$_unfrog" != "true" ]; then
	  if [ "$_NOLIB32" = "wow64" ] && ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 765ea3470ad96dfcbd8ce4c239225206ea41be8a HEAD ); then
	    _patchname='enable_dynamic_wow64_def.patch' && _patchmsg="Enable WINEARCH=wow64 by default" && nonuser_patcher
	  fi
	fi
