#!/bin/bash

# Following upstream commit acad49573a7846c0199ea3a8f1bd11c42d647ff4
if [ "$_use_staging" = "true" ] && ( cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor aeddc191a7a21996ad8d2176247e850f3e3df798 HEAD ); then
  warning "Hotfix: Fix for staging d3d12core"
  _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/staging_aeddc19_SOURCES/staging_d3d12core)
  _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/staging_aeddc19_SOURCES/staging_windows.networking.connectivity)
fi
