#!/bin/bash

	if [ "$_proton_mf_patches" = "true" ] && git merge-base --is-ancestor b073859675060c9211fcbccfd90e4e87520dc2c2 HEAD; then
	  if [ "$_use_staging" = "true" ]; then
	    if git merge-base --is-ancestor c767b6a641534a3c6c5ab2dab80290016421fcc5 HEAD; then
	      _patchname='gstreamer-patch1.patch' && _patchmsg="Applied Proton 10 MF patches - part 1" && nonuser_patcher
	      _patchname='gstreamer-patch2.patch' && _patchmsg="Applied Proton 10 MF patches - part 2" && nonuser_patcher
	    elif git merge-base --is-ancestor 01e9e725f933a28d6e13a9c827c2a33225608f80 HEAD; then
	      _patchname='gstreamer-patch1-c767b6a6.patch' && _patchmsg="Applied Proton 10 MF patches - part 1" && nonuser_patcher
	      _patchname='gstreamer-patch2.patch' && _patchmsg="Applied Proton 10 MF patches - part 2" && nonuser_patcher
	    elif git merge-base --is-ancestor ad6e820016b6972daaf3f1a66d3f9726a417641e HEAD; then
	      _patchname='gstreamer-patch1-c767b6a6.patch' && _patchmsg="Applied Proton 10 MF patches - part 1" && nonuser_patcher
	      _patchname='gstreamer-patch2-01e9e725.patch' && _patchmsg="Applied Proton 10 MF patches - part 2" && nonuser_patcher
	    elif git merge-base --is-ancestor 5bbe08a78c54eeb1f8528ca41ac0cd99928cccf7 HEAD; then
	      _patchname='gstreamer-patch1-ad6e8200.patch' && _patchmsg="Applied Proton 10 MF patches - part 1" && nonuser_patcher
	      _patchname='gstreamer-patch2-ad6e8200.patch' && _patchmsg="Applied Proton 10 MF patches - part 2" && nonuser_patcher
		elif git merge-base --is-ancestor 7f833db11ffea4f3f4fa07be31d30559aff9c5fb HEAD; then
		  _patchname='gstreamer-patch1-c767b6a6.patch' && _patchmsg="Applied Proton 10 MF patches - part 1" && nonuser_patcher
		  _patchname='gstreamer-patch2-5bbe08a7.patch' && _patchmsg="Applied Proton 10 MF patches - part 2" && nonuser_patche
		else
	      _patchname='gstreamer-patch1-7f833db1.patch' && _patchmsg="Applied Proton 10 MF patches - part 1" && nonuser_patcher
	      _patchname='gstreamer-patch2-7f833db1.patch' && _patchmsg="Applied Proton 10 MF patches - part 2" && nonuser_patcher
		fi
	  else
	    if git merge-base --is-ancestor c767b6a641534a3c6c5ab2dab80290016421fcc5 HEAD; then
	      _patchname='gstreamer-patch1.patch' && _patchmsg="Applied Proton 10 MF patches - part 1" && nonuser_patcher
	      _patchname='gstreamer-patch2-non-staging.patch' && _patchmsg="Applied Proton 10 MF patches - part 2" && nonuser_patcher
	    elif git merge-base --is-ancestor 01e9e725f933a28d6e13a9c827c2a33225608f80 HEAD; then
	      _patchname='gstreamer-patch1-c767b6a6.patch' && _patchmsg="Applied Proton 10 MF patches - part 1" && nonuser_patcher
	      _patchname='gstreamer-patch2-non-staging.patch' && _patchmsg="Applied Proton 10 MF patches - part 2" && nonuser_patcher
	    elif git merge-base --is-ancestor ad6e820016b6972daaf3f1a66d3f9726a417641e HEAD; then
	      _patchname='gstreamer-patch1-c767b6a6.patch' && _patchmsg="Applied Proton 10 MF patches - part 1" && nonuser_patcher
	      _patchname='gstreamer-patch2-non-staging-01e9e725.patch' && _patchmsg="Applied Proton 10 MF patches - part 2" && nonuser_patcher
	    elif git merge-base --is-ancestor 5bbe08a78c54eeb1f8528ca41ac0cd99928cccf7 HEAD; then
	      _patchname='gstreamer-patch1-ad6e8200.patch' && _patchmsg="Applied Proton 10 MF patches - part 1" && nonuser_patcher
	      _patchname='gstreamer-patch2-non-staging-ad6e8200.patch' && _patchmsg="Applied Proton 10 MF patches - part 2" && nonuser_patcher
		elif git merge-base --is-ancestor 7f833db11ffea4f3f4fa07be31d30559aff9c5fb HEAD; then
		  _patchname='gstreamer-patch1-c767b6a6.patch' && _patchmsg="Applied Proton 10 MF patches - part 1" && nonuser_patcher
		  _patchname='gstreamer-patch2-non-staging-5bbe08a7.patch' && _patchmsg="Applied Proton 10 MF patches - part 2" && nonuser_patche
		else
	      _patchname='gstreamer-patch1-7f833db1.patch' && _patchmsg="Applied Proton 10 MF patches - part 1" && nonuser_patcher
	      _patchname='gstreamer-patch2-7f833db1.patch' && _patchmsg="Applied Proton 10 MF patches - part 2" && nonuser_patcher
		fi
	  fi
	fi
