#!/bin/bash

	# Use faudio for xaudio2
	if git merge-base --is-ancestor d5a372abbba2e174de78855bdd4a004b56cdc006 HEAD; then # include: Move inline assembly definitions to a new wine/asm.h header.
	  _use_faudio="true"
	fi
	if [ "$_use_faudio" = "true" ] && [ "$_use_staging" = "true" ]; then
	  cd "${srcdir}"/"${_stgsrcdir}"
	  if ! git merge-base --is-ancestor b95b9109b824d21d98329c76387c3983d6e27cc2 HEAD; then
	    cd "${srcdir}"/"${_winesrcdir}"
	    if git merge-base --is-ancestor 9422b844b59282db04af533451f50661de56b9ca HEAD; then
	      _staging_args+=(-W xaudio2-revert -W xaudio2_7-CreateFX-FXEcho -W xaudio2_7-WMA_support -W xaudio2_CommitChanges) # Disable xaudio2 staging patchsets for faudio
	    elif git merge-base --is-ancestor 47fbcece36cad190c4d18f7636df67d1382b7545 HEAD && ! git merge-base --is-ancestor 3e390b1aafff47df63376a8ca4293c515d74f4ba HEAD; then
	      _patchname='faudio-exp.patch' && _patchmsg="Applied faudio for xaudio2 patch" && nonuser_patcher
	      _staging_args+=(-W xaudio2_7-CreateFX-FXEcho -W xaudio2_7-WMA_support -W xaudio2_CommitChanges) # Disable xaudio2 staging patchsets for faudio
	    fi
	  fi
	  cd "${srcdir}"/"${_winesrcdir}"
	fi
