#!/bin/bash
	# SDL Joystick support - from Proton 10 (Only for Wine 10.15+)
	if [ "$_sdl_joy_support" = "true" ]; then
	  if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 72dc2afb1a78f88cd930d61a20498838a3bea271 HEAD ); then
	    _patchname='proton10-sdl-joy.patch' && _patchmsg="Enable SDL Joystick support (from Proton)" && nonuser_patcher
	  fi
	fi

	# SDL Joystick support - from Proton
	if [ "$_sdl_joy_support" = "true" ] && [ "$_use_staging" = "true" ] && ( cd "${srcdir}"/"${_winesrcdir}" && ! git merge-base --is-ancestor 72dc2afb1a78f88cd930d61a20498838a3bea271 HEAD ); then
	  if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 13d8571b082102e030783bb13d6391b312c74aab HEAD ); then
	    _patchname='proton-sdl-joy.patch' && _patchmsg="Enable SDL Joystick support (from Proton)" && nonuser_patcher
	  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor d1d15757a44c59122b0592957597deaad06169c6 HEAD ); then
	    _patchname='proton-sdl-joy-13d8571.patch' && _patchmsg="Enable SDL Joystick support (from Proton)" && nonuser_patcher
	  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor b57f635f22091674d9e249cb5e919bda45e8afb3 HEAD ); then # Proton 7.0
	    _patchname='proton-sdl-joy-d1d1575.patch' && _patchmsg="Enable SDL Joystick support (from Proton)" && nonuser_patcher
	  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 872dc83e81c942d17a39700c4b520a6e92ddbdf2 HEAD ); then # Proton 7.0
	    _patchname='proton-sdl-joy-b57f635.patch' && _patchmsg="Enable SDL Joystick support (from Proton)" && nonuser_patcher
	  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 077d64bdbd0dcecf3f511976b4224750b7bc02dc HEAD ); then # Proton 7.0
	    _patchname='proton-sdl-joy-872dc83.patch' && _patchmsg="Enable SDL Joystick support (from Proton)" && nonuser_patcher
	  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor de280569a1d05905d9bd1abd89526aecf4dd3e81 HEAD ); then # Proton 7.0
	    _patchname='proton-sdl-joy-077d64b.patch' && _patchmsg="Enable SDL Joystick support (from Proton)" && nonuser_patcher
	  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 9aa1d0a1a79647a8b575f6a68473392e16a5efcb HEAD ); then # Proton 7.0
	    _patchname='proton-sdl-joy-de28056.patch' && _patchmsg="Enable SDL Joystick support (from Proton)" && nonuser_patcher
	  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor e4105a71d1449355563e1bf23349826d416d53f1 HEAD ); then # Proton 7.0
	    _patchname='proton-sdl-joy-9aa1d0a.patch' && _patchmsg="Enable SDL Joystick support (from Proton)" && nonuser_patcher
	  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 656edbb508d51cbe3155d856ee3f2c27a6cd4cba HEAD ); then # Proton 7.0
	    _patchname='proton-sdl-joy-e4105a7.patch' && _patchmsg="Enable SDL Joystick support (from Proton)" && nonuser_patcher
	  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 43f0c8096b2d81052a30d8542372adc46dab8292 HEAD ); then
	    _patchname='proton-sdl-joy-656edbb.patch' && _patchmsg="Enable SDL Joystick support (from Proton)" && nonuser_patcher
	  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 914633723383f321303d78eb62cb19e8a6fb7bb4 HEAD ); then
	    _patchname='proton-sdl-joy-43f0c80.patch' && _patchmsg="Enable SDL Joystick support (from Proton)" && nonuser_patcher
	  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 01d3527065e6f29997eb0ec88e36aeeecbf8ff76 HEAD ); then
	    _patchname='proton-sdl-joy-9146337.patch' && _patchmsg="Enable SDL Joystick support (from Proton)" && nonuser_patcher
	  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 828b9b8cc49fe24a306235c056a38c7ae079560f HEAD ); then
	    _patchname='proton-sdl-joy-01d3527.patch' && _patchmsg="Enable SDL Joystick support (from Proton)" && nonuser_patcher
	  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 2bd3c9703d3385820c1829a78ef71e7701d3a77a HEAD ); then
	    _patchname='proton-sdl-joy-828b9b8.patch' && _patchmsg="Enable SDL Joystick support (from Proton)" && nonuser_patcher
	  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor a17367291104e46c573b7213ee94a0f537563ace HEAD ); then
	    _patchname='proton-sdl-joy-5fe1031.patch' && _patchmsg="Enable SDL Joystick support (from Proton)" && nonuser_patcher
	  elif [ "$_EXTERNAL_INSTALL" = "proton" ] && [ "$_unfrog" != "true" ]; then
	    if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor f34b735eba04ee1deeba1e9bbf151956a23b81f2 HEAD ) && [ "$_use_staging" = "true" ]; then
	      _patchname='proton-sdl-joy-a173672.patch' && _patchmsg="Enable SDL Joystick support (from Proton)" && nonuser_patcher
	    elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 27f40156baa7f1e09c6e420f6c278606557a505a HEAD ) && [ "$_use_staging" = "true" ]; then
	      _patchname='proton-sdl-joy-f34b735.patch' && _patchmsg="Enable SDL Joystick support (from Proton)" && nonuser_patcher
	    elif ( cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor 661df7b889bb973721d09a316d87d200a31233fe HEAD ) && [ "$_use_staging" = "true" ]; then
	      _patchname='proton-sdl-joy-27f4015.patch' && _patchmsg="Enable SDL Joystick support (from Proton)" && nonuser_patcher
	    elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 626870abe2e800cc9407d05d5c00500a4ad97b3a HEAD ) && [ "$_use_staging" = "true" ]; then
	      _patchname='proton-sdl-joy-661df7b.patch' && _patchmsg="Enable SDL Joystick support (from Proton)" && nonuser_patcher
	    elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor b71cea76ed24ca940783e01da54917eefa0bb36b HEAD ) && [ "$_use_staging" = "true" ]; then
	      _patchname='proton-sdl-joy-626870a.patch' && _patchmsg="Enable SDL Joystick support (from Proton)" && nonuser_patcher
	    elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor e4fbae832c868e9fcf5a91c58255fe3f4ea1cb30 HEAD ) && [ "$_use_staging" = "true" ]; then
	      _patchname='proton-sdl-joy-b71cea7.patch' && _patchmsg="Enable SDL Joystick support (from Proton)" && nonuser_patcher
	    elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 6373792eec0f122295723cae77b0115e6c96c3e4 HEAD ) && [ "$_use_staging" = "true" ]; then
	      _patchname='proton-sdl-joy-e4fbae8.patch' && _patchmsg="Enable SDL Joystick support (from Proton)" && nonuser_patcher
	    elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 0c249e6125fc9dc6ee86b4ef6ae0d9fa2fc6291b HEAD ); then
	      _patchname='proton-sdl-joy-6373792.patch' && _patchmsg="Enable SDL Joystick support (from Proton)" && nonuser_patcher
	    elif git merge-base --is-ancestor 306c40e67319cae8e4c448ec8fc8d3996f87943f HEAD; then
	      _patchname='proton-sdl-joy-0c249e6.patch' && _patchmsg="Enable SDL Joystick support (from Proton)" && nonuser_patcher
	    elif git merge-base --is-ancestor b87256cd1db21a59484248a193b6ad12ca2853ca HEAD; then
	      _patchname='proton-sdl-joy-306c40e.patch' && _patchmsg="Enable SDL Joystick support (from Proton) (<306c40e)" && nonuser_patcher
	    else
	      _patchname='proton-sdl-joy-b87256c.patch' && _patchmsg="Enable SDL Joystick support (from Proton) (<b87256c)" && nonuser_patcher
	    fi
	    if ( git merge-base --is-ancestor 1daeef73325e9d35073231baf874600050126c7f HEAD && ! git merge-base --is-ancestor 6373792eec0f122295723cae77b0115e6c96c3e4 HEAD ); then
	      _patchname='proton-sdl-joy-2.patch' && _patchmsg="Enable SDL Joystick support additions (from Proton)" && nonuser_patcher
	    fi
	    source "$_where"/wine-tkg-patches/proton-tkg-specific/proton-gamepad-additions/proton-gamepad-additions
	  fi
	fi
