#!/bin/bash

	# Proton EAC
	if [ "$_proton_eac_support" = "true" ] && [ "$_unfrog" != "true" ]; then
	  if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 64f7c37c9561274be931389ff9ebe586b8e0d6b6 HEAD ); then
	    _patchname='Revert-ntdll-Get-rid-of-the-wine_nt_to_unix_file_nam.patch' && _patchmsg="Revert ntdll: Get rid of the wine_nt_to_unix_file_name syscall" && nonuser_patcher
	    _patchname='proton-eac_bridge.patch' && _patchmsg="Add support for Proton's EAC bridge" && nonuser_patcher
	  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor fd1153552d779e1ac14b0b1c48fbd1cde894eb0a HEAD ); then
	    _patchname='Revert-ntdll-Get-rid-of-the-wine_nt_to_unix_file_nam-64f7c37c.patch' && _patchmsg="Revert ntdll: Get rid of the wine_nt_to_unix_file_name syscall" && nonuser_patcher
	    _patchname='proton-eac_bridge.patch' && _patchmsg="Add support for Proton's EAC bridge" && nonuser_patcher
	  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor bf42dca35f05bce9996e91f59cc47b5a9e6996b2 HEAD ); then
	    _patchname='proton-eac_bridge-fd11535.patch' && _patchmsg="Add support for Proton's EAC bridge" && nonuser_patcher
	  fi
	  if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 8c3f205696571558a6fae42314370fbd7cc14a12 HEAD ); then
	    _patchname='wow64_loader_hack.patch' && _patchmsg="Hack around loader name for EAC on 10.2+" && nonuser_patcher
	  fi
	fi
