#!/bin/bash

# https://bugs.winehq.org/show_bug.cgi?id=53038
if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 182feddd4b02e83f3c69863bc2e6e63945eb2df1 HEAD && ! git merge-base --is-ancestor 5f680a1e1cecc8a3d1e875bb3339acdec8139cd3 HEAD ); then
  warning "Hotfix: Fix for EGS 'divide by zero in 64-bit code' error on 7.9"
  _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/EGS/dwmapi_EGS_fixup)
fi

