#!/bin/bash

# https://bugs.winehq.org/show_bug.cgi?id=51262 - 32-bit apps are broken by 308a5e7c4d01525184b057058949c68c0ee77dba - Fix by Zebediah Figura
if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 308a5e7c4d01525184b057058949c68c0ee77dba HEAD && ! git merge-base --is-ancestor 79c102d6bec81b79e10290f23e9ac3816da6b58f HEAD ); then
  warning "Hotfix: Fix for 32-bit programs not starting since 308a5e7"
  _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/308a5e7c/ntdll_reserve_space_for_the_whole_64-bit_YMM_context)
fi
