#!/bin/bash

# Fix steamhelper breaking with 0c19e2e
if [ "$_proton_use_steamhelper" = "true" ] && ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 0c19e2e487d36a89531daf4897c0b6390d82a843 HEAD ) && ( cd "${srcdir}"/"${_winesrcdir}" && ! git merge-base --is-ancestor 27040a4f009f1e35a540882dc150d14431de64a8 HEAD ); then
  warning "Hotfix: Fix for steam-helper breakage"
  _hotfix_mainlinereverts+=(4a1bd593f39b0852ca8fccbf0e54f7c00b3783ec 0c19e2e487d36a89531daf4897c0b6390d82a843)
  _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/shell32-Progress_Dialog/shell32-Progress_Dialog-staging-41e1551)
fi
