#!/bin/bash

	# Workaround for https://bugs.winehq.org/show_bug.cgi?id=47633
	if [ "$_nativedotnet_fix" = "true" ] && git merge-base --is-ancestor 0116660dd80b38da8201e2156adade67fc2ae823 HEAD && ! git merge-base --is-ancestor 505be3a0a2afeae3cebeaad48fc5f32e0b0336b7 HEAD; then
	  _patchname='0001-kernelbase-Remove-DECLSPEC_HOTPATCH-from-SetThreadSt.patch' && _patchmsg="Applied native dotnet workaround (https://bugs.winehq.org/show_bug.cgi?id=47633)" && nonuser_patcher
	fi
