#!/bin/bash

# 6dcaff4 breaks childwindow patches (from fshack or standalone), so let's revert the changes for now
if ( cd "${srcdir}"/"${_winesrcdir}" && ! git merge-base --is-ancestor 548bc54bf396d74b5b928bf9be835272ddda1886 HEAD ); then
  if [ "$_proton_fs_hack" = "true" ] || [ "$_childwindow_fix" = "true" ] && ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 6dcaff421f87a93efe18b2efe0ec64d94ed1d483 HEAD ); then
  _hotfix_mainlinereverts+=(548bc54bf396d74b5b928bf9be835272ddda1886 b502a3e3c6b43ac3947d85ccc263e729ace917fa 963589ee296ae90003dab3e8204766ab4e4c0045 2adf4376d86119b8a6f7cde51c9a972564575bac 6dcaff421f87a93efe18b2efe0ec64d94ed1d483)
  _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/childwindow/staging-6dcaff42)
    if ( cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor 4c51f4f5f6ddecd47a3121a8ce4228d4763892b4 HEAD ); then
    _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/childwindow/staging-4c51f4f)
    fi
  elif [ "$_protonify" = "true" ] && ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor b502a3e3c6b43ac3947d85ccc263e729ace917fa HEAD ); then
    _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/childwindow/b502a3e-proton)
  fi
elif [ "$_proton_fs_hack" != "true" ] && [ "$_childwindow_fix" = "true" ] && ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 548bc54bf396d74b5b928bf9be835272ddda1886 HEAD ); then
  if [ "$_use_staging" = "true" ] && ( cd "${srcdir}"/"${_winesrcdir}" && ! git merge-base --is-ancestor d318f43559dbb0093e22bab1aa0eb9dc01170cc2 HEAD ); then
    warning "Hotfix: Standalone vulkan childwindow support disabled on this revision. Please enable fshack as a workaround."
    _childwindow_fix="false"
  elif [ "$_use_staging" = "false" ]; then
    warning "Hotfix: Standalone vulkan childwindow support disabled on this revision. Please enable staging as a workaround."
    _childwindow_fix="false"
  fi
elif ( cd "${srcdir}"/"${_winesrcdir}" && ! git merge-base --is-ancestor 656edbb508d51cbe3155d856ee3f2c27a6cd4cba HEAD ); then
  if [ "$_proton_fs_hack" = "true" ] && ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 9aef654392756aacdce6109ccbe21ba446ee4387 HEAD ); then
    _hotfix_mainlinereverts+=(ef9c0b3f691f6897f0acfd72af0a9ea020f0a0bf 3b8d7f7f036f3f4771284df97cce99d114fe42cb fe5e06185dfc828b5d3873fd1b28f29f15d7c627 6ef7cd4e3ae54d6ed09d85a2518e7e64d7f03573 c2384cf23378953b6960e7044a0e467944e8814a c3862f2a6121796814ae31913bfb0efeba565087 37be0989540cf84dd9336576577ae535f2b6bbb8 3661194f8e8146a594673ad3682290f10fa2c096 9aef654392756aacdce6109ccbe21ba446ee4387)
    _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/rdr2/0004-winevulkan1)
    _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/childwindow/staging-fa5989b)
    if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor f0cd33c69e879177559caaf248e86a4d69f9a09e HEAD ); then
      _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/childwindow/f0cd33c)
    fi
  elif [ "$_proton_fs_hack" = "false" ] && ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 9aef654392756aacdce6109ccbe21ba446ee4387 HEAD ); then
    _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/rdr2/0004-winevulkan2)
  fi
fi
