#!/bin/bash

# community patches
if [[ ${_community_patches[*]} =~ "winex11-fs-no_above_state.mypatch" ]]; then
  if [ "$_proton_fs_hack" != "true" ] && [ "$_hotfixes_no_confirm" != "true" ]; then
    warning "HALP! You have enabled winex11-fs-no_above_state community patch, but its _proton_fs_hack dependency is disabled."
    read -rp "Enable _proton_fs_hack to fix it?"$'\n> Y/n : ' _hotfixansw;
  fi
  if ( [ "$_hotfixansw" != "n" ] && [ "$_hotfixansw" != "N" ] ) || [ "$_hotfixes_no_confirm" = "true" ]; then
    _proton_fs_hack="true"
  fi
fi

if [[ ${_community_patches[*]} =~ "guy1524_mfplat_WIP.mypatch" ]]; then
  if [ "$_proton_mf_hacks" = "true" ] && [ "$_hotfixes_no_confirm" != "true" ]; then
    warning "HALP! You have enabled guy1524_mfplat_WIP community patch, but the potentially conflicting _proton_mf_hacks option is also enabled."
    read -rp "Disable _proton_mf_hacks to fix it?"$'\n> Y/n : ' _hotfixansw;
  fi
  if ( [ "$_hotfixansw" != "n" ] && [ "$_hotfixansw" != "N" ] ) || [ "$_hotfixes_no_confirm" = "true" ]; then
    _proton_mf_hacks="false"
  fi
fi
# /community patches

# Broken staging fbe1ba5
if ( cd "${srcdir}"/"${_stgsrcdir}" && [ "$(git rev-parse HEAD)" = "fbe1ba5578fb7380e2b09a5aebf5aa488744a823" ] ); then
  warning "Fixing wrong staging upstream commit... Should be 4358ddc75fbfabdc4a4f31b4e3cc9aa1e0811d4c"
  sed -i 's|echo "3bb824f98891e8eb907c9c652fe528373a17b10d"|echo "4358ddc75fbfabdc4a4f31b4e3cc9aa1e0811d4c"|g' "${srcdir}"/"${_stgsrcdir}"/patches/patchinstall.sh
fi

# Broken staging f329843
if ( cd "${srcdir}"/"${_stgsrcdir}" && [ "$(git rev-parse HEAD)" = "f3298432f0c4614a7554e06c6c9a66ef3623ead8" ] ); then
  warning "Fixing wrong staging upstream commit... Should be 8257fe88fb99ca0bdeec27b47b7cf835bda5c061"
  sed -i 's|echo "ba920246e502afe7bc664c1881d528a27e980101"|echo "8257fe88fb99ca0bdeec27b47b7cf835bda5c061"|g' "${srcdir}"/"${_stgsrcdir}"/patches/patchinstall.sh
fi

# Broken staging 215d78f8 - 3f3a05f9
if ( cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor 215d78f8e18bced54b97b39fcf71ebbb2a3ab13c HEAD && ! git merge-base --is-ancestor 3f3a05f91c85cb5ccdc4c8185bcc862c6e96cd52 HEAD ); then
  warning "Disable broken xactengine-initial patchset on staging 215d78f8+"
  _staging_args+=(-W xactengine-initial)
fi

# Broken staging 4ef21bcf
if ( cd "${srcdir}"/"${_stgsrcdir}" && [ "$(git rev-parse HEAD)" = "4ef21bcf82f625cce4c487c34ab695e61388afb6" ] ); then
  warning "Disable broken dsound-EAX patchset on staging 4ef21bcf"
  _staging_args+=(-W dsound-EAX)
fi

# Broken staging d9eb78e5 - 03290f8a
if ( cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor d9eb78e597833fcafeb3d957a3b7dd6fc3afaa0e HEAD && ! git merge-base --is-ancestor 03290f8a41a61188758b5e0ec1236046367d1497 HEAD ); then
  warning "Disable broken ole32-HGLOBALStream patchset on staging d9eb78e5+"
  _staging_args+=(-W ole32-HGLOBALStream)
fi
