#!/bin/bash

# community patches
if [[ ${_community_patches[*]} =~ "winex11-fs-no_above_state.mypatch" ]]; then
  if [ "$_proton_fs_hack" != "true" ] && [ "$_hotfixes_no_confirm" != "true" ]; then
    warning "HALP! You have enabled winex11-fs-no_above_state community patch, but its _proton_fs_hack dependency is disabled."
    read -rp "Enable _proton_fs_hack to fix it?"$'\n> Y/n : ' _hotfixansw;
  fi
  if ( [ "$_hotfixansw" != "n" ] && [ "$_hotfixansw" != "N" ] ) || [ "$_hotfixes_no_confirm" = "true" ]; then
    _proton_fs_hack="true"
  fi
fi

if [[ ${_community_patches[*]} =~ "guy1524_mfplat_WIP.mypatch" ]]; then
  if [ "$_proton_mf_hacks" = "true" ] && [ "$_hotfixes_no_confirm" != "true" ]; then
    warning "HALP! You have enabled guy1524_mfplat_WIP community patch, but the potentially conflicting _proton_mf_hacks option is also enabled."
    read -rp "Disable _proton_mf_hacks to fix it?"$'\n> Y/n : ' _hotfixansw;
  fi
  if ( [ "$_hotfixansw" != "n" ] && [ "$_hotfixansw" != "N" ] ) || [ "$_hotfixes_no_confirm" = "true" ]; then
    _proton_mf_hacks="false"
  fi
fi
# /community patches

# Broken staging fbe1ba5 - legacy
if ( cd "${srcdir}"/"${_stgsrcdir}" && [ "$(git rev-parse HEAD)" = "fbe1ba5578fb7380e2b09a5aebf5aa488744a823" ] ); then
  warning "Fixing wrong staging upstream commit... Should be 4358ddc75fbfabdc4a4f31b4e3cc9aa1e0811d4c"
  sed -i 's|echo "3bb824f98891e8eb907c9c652fe528373a17b10d"|echo "4358ddc75fbfabdc4a4f31b4e3cc9aa1e0811d4c"|g' "${srcdir}"/"${_stgsrcdir}"/patches/patchinstall.sh
fi

# Broken staging f329843 - legacy
if ( cd "${srcdir}"/"${_stgsrcdir}" && [ "$(git rev-parse HEAD)" = "f3298432f0c4614a7554e06c6c9a66ef3623ead8" ] ); then
  warning "Fixing wrong staging upstream commit... Should be 8257fe88fb99ca0bdeec27b47b7cf835bda5c061"
  sed -i 's|echo "ba920246e502afe7bc664c1881d528a27e980101"|echo "8257fe88fb99ca0bdeec27b47b7cf835bda5c061"|g' "${srcdir}"/"${_stgsrcdir}"/patches/patchinstall.sh
fi

# Broken staging 215d78f8
if ( cd "${srcdir}"/"${_stgsrcdir}" && [ "$(git rev-parse HEAD)" = "215d78f8e18bced54b97b39fcf71ebbb2a3ab13c" ] ); then
  warning "Disable broken xactengine-initial patchset on staging 215d78f8e18bced54b97b39fcf71ebbb2a3ab13c"
  _staging_args+=(-W xactengine-initial)
fi
