#!/bin/bash

# Fix wine freeze when run with wine wayland driver
if [ "$_wayland_driver" = "true" ] && ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor fe7e94d58c2596c23b407c5a0cd11b57f001d4dd HEAD ); then
  _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/winewayland/winewayland-avoid-crashing)
  warning "Hotfix: Fix wayland driver crash"
fi
