#!/bin/bash

# Fix Weird behavior on vulkan caused by regression
if [ "$_wayland_driver" = "true" ] && ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor de0fc7fd95074cfdeb032d36246c56247d2bd82b HEAD); then
  if [ "$_hotfixes_no_confirm" != "true" ] && [ "$_hotfixes_no_confirm" != "ignore" ]; then
    warning "Hotfix: Upstream commit de0fc7f cause flickering in DXVK and VKD3D on winewayland."
    read -rp "Are you okay to revert this ?"$'\n> N/y : ' _hotfixansw;
  fi
  if [[ "$_hotfixansw" =~ [yY] ]] || [ "$_hotfixes_no_confirm" = "true" ]; then
    _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/winewayland/de0fc7fd95074cfdeb032d36246c56247d2bd82b)
  fi
fi

# Fix wine freeze when run with wine wayland driver
if [ "$_wayland_driver" = "true" ] && ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor fe7e94d58c2596c23b407c5a0cd11b57f001d4dd HEAD && ! git merge-base --is-ancestor 1e701a6b3798ecfd688ad1ff405dbb62b3d214c6 HEAD ); then
  _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/winewayland/winewayland-avoid-crashing)
  warning "Hotfix: Fix wayland driver crash"
fi
