#!/bin/bash

# Star Citizen 3.17.1 hotfix - https://bugs.winehq.org/show_bug.cgi?id=52956
if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor d4cfb0c30c74cbb53291ef660ade50091a7901be HEAD ); then
  _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/SetThreadInformation/SetThreadInformation)
fi
