#!/bin/bash

# Multiple games making use of mfplat broke with 1fceb1213992b79aa7f1a5dc0a72ab3756ee524d
# Prevent crashing in multiple affected games with Derek's implementation: https://raw.githubusercontent.com/wine-staging/wine-staging/0ae7315541c8847d902c9e458a928c4df5520ba6/patches/mfplat-streaming-support/0033-HACK-Switch-between-all-selection-streams-on-MF_SOUR.patch
if [ "$_use_staging" = "true" ] && ( cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor 41e15516bde2e7c96fdb229c17140bf52fb05403 HEAD ) && ( cd "${srcdir}"/"${_stgsrcdir}" && ! git merge-base --is-ancestor 09fdb3b5c97df1b96389f8070fd791560ec670b4 HEAD ); then
  warning "Hotfix: Fix for mfplat breakage in some games"
  _hotfix_mainlinereverts+=(a67d7c15336ea5caa89099952da1fc1998188029 a0a6fad695d2f9d1eb2601725ac27c9a9949026b beb9c6578ad8e21eb4b34366dbc3dff8b8c2ae5d cf4fe13a41b7cc0a624da7741ae528ef21032736 1fceb1213992b79aa7f1a5dc0a72ab3756ee524d)
  _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/mfplat/mfplat-derek-hotfix)
elif [ "$_use_staging" = "true" ] && ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 1fceb1213992b79aa7f1a5dc0a72ab3756ee524d HEAD ) && ( cd "${srcdir}"/"${_stgsrcdir}" && ! git merge-base --is-ancestor 41e15516bde2e7c96fdb229c17140bf52fb05403 HEAD ); then
  warning "Hotfix: Fix for mfplat breakage in some games"
  _hotfix_mainlinereverts+=(1fceb1213992b79aa7f1a5dc0a72ab3756ee524d)
  _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/mfplat/mfplat-derek-hotfix)
fi
