#!/bin/bash

# Reverts due to broken input on The Witcher 3 and others - https://bugs.winehq.org/show_bug.cgi?id=53487
if ( [ "$_use_staging" = "true" ] && [ "$_proton_fs_hack" != "true" ] || [ "$_use_staging" = "false" ] ) && ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor a2395ecf963b85ca0ea2f002982af07fc8241db9 HEAD && ! git merge-base --is-ancestor a42b22e027e2be20f7f3a924eddeee92b7bbc99d HEAD ); then
  warning "Workaround The Witcher 3 losing kb inputs on 7.14"
  #_hotfix_mainlinereverts+=(4304a677c1c35443318cb067b90a83b81afec6ba a2395ecf963b85ca0ea2f002982af07fc8241db9 1587e9db88c8ad1afe4401290ce130664a5a4a40 c484e4b87ead26389b6192b3be672348d4218520 37a3c916b447bab5932ae202c053bceaba46e594)
  _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/a2395ecf/rbernon_pending)
  # Staging
  #if ( cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor 87083566479467a536b2d3d373e3ef28ab517875 HEAD ); then
  #  _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/a2395ecf/witcher3-input-staging)
  #fi
fi

