#!/bin/bash

	  if [ "$_wined3d_additions" = "true" ] && [ "$_use_staging" = "false" ]; then
	    _patchname='proton-wined3d-additions.patch' && _patchmsg="Enable Proton non-vr-related wined3d additions" && nonuser_patcher
	  fi
