#!/bin/bash

	# Proton Bcrypt patches
	if [ "$_proton_bcrypt" = "true" ]; then
	  if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 74c0da2d71e95f3e6bd6c8b440652933771b27d7 HEAD );then
	    if [ "$_use_staging" = "true" ] && ( [ -e "${srcdir}/${_stgsrcdir}/patches/bcrypt-ECDHSecretAgreement/definition" ] && ! grep -Fxq 'Disabled: true' "${srcdir}/${_stgsrcdir}/patches/bcrypt-ECDHSecretAgreement/definition" ); then
	      if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor b3cd21c21cf832529b154b3b8cc6ff85ec246c59 HEAD );then
	        _patchname='proton-bcrypt-staging.patch' && _patchmsg="Using Proton Bcrypt patches" && nonuser_patcher
	      elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 3db37dc5ae4e8b701c26f96fec97822b8b4da80c HEAD );then
	        _patchname='proton-bcrypt-staging-b3cd21c.patch' && _patchmsg="Using Proton Bcrypt patches" && nonuser_patcher
	      else
	        _patchname='proton-bcrypt-staging-3db37dc.patch' && _patchmsg="Using Proton Bcrypt patches" && nonuser_patcher
	      fi
	      ( cd "${srcdir}"/"${_winesrcdir}" && update_configure )
	    fi
	  fi
	fi
