#!/bin/bash

# Revert d4259ac8e9326a8173d6f83f0d525c97b90a1da0 which breaks compiling the steam helper
if [ "$_EXTERNAL_INSTALL" = "proton" ]; then
  if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 6bcdbbe5736f8c5f9adb1c4c687a3f23a4e5c261 HEAD ); then
    _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/mingw-msvcrt-steamhelper/d4259ac8e93)
  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 9ae627316d98b3a0399bd6b5c2257bd47d596bc6 HEAD ); then
    _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/mingw-msvcrt-steamhelper/d4259ac8e93-6bcdbbe)
  else
    _hotfix_mainlinereverts+=(d4259ac8e9326a8173d6f83f0d525c97b90a1da0)
  fi
fi
