#!/bin/bash

	  # tabtip - 7.2+
	  if [ "$_EXTERNAL_INSTALL" = "proton" ] && [ "$_tabtip" = "true" ]; then
	    if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 26637de7cbc770cab20c6e35a828cc9e93fcfc9d HEAD ); then
	      _patchname='proton-tabtip.patch' && _patchmsg="Enable Proton's SteamDeck additions" && nonuser_patcher
	    elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor bf42dca35f05bce9996e91f59cc47b5a9e6996b2 HEAD ); then
	      _patchname='proton-tabtip-26637de.patch' && _patchmsg="Enable Proton's SteamDeck additions" && nonuser_patcher
	    fi
	  fi
