#!/bin/bash

# Fix for battle.net launcher
if [ "$_battlenet_fix" = "true" ] && ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 65124f15acc5705eb159d5d920877f0ac4835d27 HEAD ); then
  _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/battlenet/battlenet)
  warning "Hotfix: Fix for Battle.Net launcher"
fi
