#!/bin/bash

# Fix for battle.net launcher
if [ "$_use_staging" = "true" ] && ( cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor c901884ac0af17eeeac309269693d959cfb45e0b HEAD && ! git merge-base --is-ancestor e68e4dbb7529295dc4fde320689f80b1215a0419 HEAD); then
  _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/battlenet/battlenet)
  warning "Hotfix: Fix for Battle.Net launcher"
fi
