#!/bin/bash

	# Proton CPU topology override - depends on protonify and fsync
	if ( [ "$_staging_esync" = "true" ] || [ "$_use_esync" = "true" ] ) && [ "$_use_fsync" = "true" ] && [ "$_protonify" = "true" ] && ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 6f158754435f403864052e595ab627dadac2666f HEAD ); then
	  if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor af4378d46dbb72e682017485212442bf865c2226 HEAD ); then
	    _patchname='proton-cpu-topology-overrides.patch' && _patchmsg="Enable Proton's CPU topology override support" && nonuser_patcher
	  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 05676e83e975816b3c0d87b4b18b5cd15a372489 HEAD ); then
	    _patchname='proton-cpu-topology-overrides-af4378d.patch' && _patchmsg="Enable Proton's CPU topology override support" && nonuser_patcher
	  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor b3ca48f39ce822c197193ffc419771f1869f3c83 HEAD ); then
	    _patchname='proton-cpu-topology-overrides-05676e8.patch' && _patchmsg="Enable Proton's CPU topology override support" && nonuser_patcher
	  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 588d91aecf2bf8ac7e9ae1de44ddc01caae52109 HEAD ); then
	    _patchname='proton-cpu-topology-overrides-b3ca48f.patch' && _patchmsg="Enable Proton's CPU topology override support" && nonuser_patcher
	  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor be8bd6f498dadbafe068c1fbb02adcbadf0b1b56 HEAD ); then
	    _patchname='proton-cpu-topology-overrides-588d91a.patch' && _patchmsg="Enable Proton's CPU topology override support" && nonuser_patcher
	  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 5864bc88de0e0a3b1094c2bb0c16ba9a5d39ce65 HEAD ); then
	    _patchname='proton-cpu-topology-overrides-be8bd6f.patch' && _patchmsg="Enable Proton's CPU topology override support" && nonuser_patcher
	  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor c88b2ed3c04fdde86fc1fca670ae862056e614da HEAD ); then
	    _patchname='proton-cpu-topology-overrides-5864bc8.patch' && _patchmsg="Enable Proton's CPU topology override support" && nonuser_patcher
	  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor a3c92a02cc7014cfdb1f90f1d070037868067097 HEAD ); then
	    _patchname='proton-cpu-topology-overrides-c88b2ed.patch' && _patchmsg="Enable Proton's CPU topology override support" && nonuser_patcher
	  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 44699c324f20690f9d6836919534ca1b5bcc3efe HEAD ); then
	    _patchname='proton-cpu-topology-overrides-a3c92a0.patch' && _patchmsg="Enable Proton's CPU topology override support" && nonuser_patcher
	  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 7999af82448c340b28e3d6e412463c5cdcc6cea6 HEAD ); then
	    _patchname='proton-cpu-topology-overrides-44699c3.patch' && _patchmsg="Enable Proton's CPU topology override support" && nonuser_patcher
	  else
	    _patchname='proton-cpu-topology-overrides-7999af8.patch' && _patchmsg="Enable Proton's CPU topology override support" && nonuser_patcher
	  fi
	fi
