#!/bin/bash

	# Proton CPU topology override - depends on protonify and fsync
	if ( [ "$_staging_esync" = "true" ] || [ "$_use_esync" = "true" ] ) && [ "$_use_fsync" = "true" ] && [ "$_protonify" = "true" ] && ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 6f158754435f403864052e595ab627dadac2666f HEAD ); then
	  if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor e397ed180d6b85b8d410e29153c7bfd297708f55 HEAD ); then
	    if [ "$_EXTERNAL_INSTALL" = "proton" ] && [ "$_unfrog" != "true" ] && [ "$_steamclient_noswap" != "true" ]; then
	      _patchname='proton-cpu-topology-overrides.patch' && _patchmsg="Enable Proton's CPU topology override support" && nonuser_patcher
	    else
	      _patchname='proton-cpu-topology-overrides-noswap.patch' && _patchmsg="Enable Proton's CPU topology override support" && nonuser_patcher
	    fi
	  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 3323a7e4474afc3509ba56eab51b76e7887f6450 HEAD ); then
	    _patchname='proton-cpu-topology-overrides-e397ed18.patch' && _patchmsg="Enable Proton's CPU topology override support" && nonuser_patcher
	  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 0559442de9c139ec2b66fee69f87a58b60df4b10 HEAD ); then
	    _patchname='proton-cpu-topology-overrides-3323a7e.patch' && _patchmsg="Enable Proton's CPU topology override support" && nonuser_patcher
	  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 25b93b219654d85cac9fdfca1581c97c40a5dcbb HEAD ); then
	    _patchname='proton-cpu-topology-overrides-0559442.patch' && _patchmsg="Enable Proton's CPU topology override support" && nonuser_patcher
	  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 75e2ec479beff86c52bebdab6d5e8b78c8f6ca8d HEAD ); then
	    _patchname='proton-cpu-topology-overrides-25b93b2.patch' && _patchmsg="Enable Proton's CPU topology override support" && nonuser_patcher
	  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 90d2a173aa9b4f8c85e5a6f653f03ecf9b6f4e22 HEAD ); then
	    _patchname='proton-cpu-topology-overrides-75e2ec4.patch' && _patchmsg="Enable Proton's CPU topology override support" && nonuser_patcher
	  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 5125f9d5affb7d838e479b6e11f6344d54943a8c HEAD ); then
	    _patchname='proton-cpu-topology-overrides-90d2a17.patch' && _patchmsg="Enable Proton's CPU topology override support" && nonuser_patcher
	  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 7e3293107f11037bab6e96266b7f4016f4e5c427 HEAD ); then
	    _patchname='proton-cpu-topology-overrides-5125f9d.patch' && _patchmsg="Enable Proton's CPU topology override support" && nonuser_patcher
	  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor e4db1b39ea28d0cc1b20ef4eacbb237c2f6cb68b HEAD ); then
	    _patchname='proton-cpu-topology-overrides-7e32931.patch' && _patchmsg="Enable Proton's CPU topology override support" && nonuser_patcher
	  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor cd5eb0f143fa13795374530c603231cff40cbb8a HEAD ); then
	    _patchname='proton-cpu-topology-overrides-e4db1b3.patch' && _patchmsg="Enable Proton's CPU topology override support" && nonuser_patcher
	  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor e05c6c821104d45344fc532a15f96360a24a0174 HEAD ); then
	    _patchname='proton-cpu-topology-overrides-cd5eb0f.patch' && _patchmsg="Enable Proton's CPU topology override support" && nonuser_patcher
	  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 59485f00c917061c097c1805d7fa7f61c380c749 HEAD ); then
	    _patchname='proton-cpu-topology-overrides-e05c6c8.patch' && _patchmsg="Enable Proton's CPU topology override support" && nonuser_patcher
	  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor a5f17fac3ee7827d5e8e6878c622084e9ad776e0 HEAD ); then
	    _patchname='proton-cpu-topology-overrides-59485f0.patch' && _patchmsg="Enable Proton's CPU topology override support" && nonuser_patcher
	  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor af4378d46dbb72e682017485212442bf865c2226 HEAD ); then
	    _patchname='proton-cpu-topology-overrides-a5f17fa.patch' && _patchmsg="Enable Proton's CPU topology override support" && nonuser_patcher
	  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 05676e83e975816b3c0d87b4b18b5cd15a372489 HEAD ); then
	    _patchname='proton-cpu-topology-overrides-af4378d.patch' && _patchmsg="Enable Proton's CPU topology override support" && nonuser_patcher
	  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor b3ca48f39ce822c197193ffc419771f1869f3c83 HEAD ); then
	    _patchname='proton-cpu-topology-overrides-05676e8.patch' && _patchmsg="Enable Proton's CPU topology override support" && nonuser_patcher
	  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 588d91aecf2bf8ac7e9ae1de44ddc01caae52109 HEAD ); then
	    _patchname='proton-cpu-topology-overrides-b3ca48f.patch' && _patchmsg="Enable Proton's CPU topology override support" && nonuser_patcher
	  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor be8bd6f498dadbafe068c1fbb02adcbadf0b1b56 HEAD ); then
	    _patchname='proton-cpu-topology-overrides-588d91a.patch' && _patchmsg="Enable Proton's CPU topology override support" && nonuser_patcher
	  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 5864bc88de0e0a3b1094c2bb0c16ba9a5d39ce65 HEAD ); then
	    _patchname='proton-cpu-topology-overrides-be8bd6f.patch' && _patchmsg="Enable Proton's CPU topology override support" && nonuser_patcher
	  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor c88b2ed3c04fdde86fc1fca670ae862056e614da HEAD ); then
	    _patchname='proton-cpu-topology-overrides-5864bc8.patch' && _patchmsg="Enable Proton's CPU topology override support" && nonuser_patcher
	  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor a3c92a02cc7014cfdb1f90f1d070037868067097 HEAD ); then
	    _patchname='proton-cpu-topology-overrides-c88b2ed.patch' && _patchmsg="Enable Proton's CPU topology override support" && nonuser_patcher
	  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 44699c324f20690f9d6836919534ca1b5bcc3efe HEAD ); then
	    _patchname='proton-cpu-topology-overrides-a3c92a0.patch' && _patchmsg="Enable Proton's CPU topology override support" && nonuser_patcher
	  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 7999af82448c340b28e3d6e412463c5cdcc6cea6 HEAD ); then
	    _patchname='proton-cpu-topology-overrides-44699c3.patch' && _patchmsg="Enable Proton's CPU topology override support" && nonuser_patcher
	  else
	    _patchname='proton-cpu-topology-overrides-7999af8.patch' && _patchmsg="Enable Proton's CPU topology override support" && nonuser_patcher
	  fi
	fi
