#!/bin/bash

# Patch opencl.h header to it's correct location without breaking successive autoconf call, as it was done by the sed workaround
if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 9207927d950ce8ab41a6d8c25cfa593ce770d5cf HEAD ); then
  warning "Hotfix: Fix for CL/opencl.h header recognition"
  _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/autoconf-opencl-hotfix/opencl-fixup)
elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 45eca854c4fab7e864deebf9a51c74147884ebc8 HEAD ); then
  warning "Hotfix: Fix for CL/opencl.h header recognition"
  _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/autoconf-opencl-hotfix/opencl-fixup-9207927)
else
  warning "Hotfix: Fix for CL/opencl.h header recognition"
  _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/autoconf-opencl-hotfix/opencl-fixup-45eca85)
fi
