#!/bin/bash

# Patch opencl.h header to it's correct location without breaking successive autoconf call, as it was done by the sed workaround
if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor f74c4af257e0856e6607d2823e4f03109111a4b6 HEAD ); then
  warning "Hotfix: Fix for CL/opencl.h header recognition"
  _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/autoconf-opencl-hotfix/opencl-fixup)
elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 9207927d950ce8ab41a6d8c25cfa593ce770d5cf HEAD ); then
  warning "Hotfix: Fix for CL/opencl.h header recognition"
  _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/autoconf-opencl-hotfix/opencl-fixup-f74c4af)
elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 45eca854c4fab7e864deebf9a51c74147884ebc8 HEAD ); then
  warning "Hotfix: Fix for CL/opencl.h header recognition"
  _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/autoconf-opencl-hotfix/opencl-fixup-9207927)
elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 34289e749f44703997e8d904aaf12ac20b691b24 HEAD ); then
  warning "Hotfix: Fix for CL/opencl.h header recognition"
  _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/autoconf-opencl-hotfix/opencl-fixup-45eca85)
else
  warning "Hotfix: Fix for CL/opencl.h header recognition - legacy edition"
  sed 's|OpenCL/opencl.h|CL/opencl.h|g' -i "${srcdir}"/"${_winesrcdir}"/configure*
fi
