#!/bin/bash

# Wine Destroyer - fd7992972b252ed262d33ef604e9e1235d2108c5
# https://bugs.winehq.org/show_bug.cgi?id=48971
# https://bugs.winehq.org/show_bug.cgi?id=49007
# https://bugs.winehq.org/show_bug.cgi?id=49025
# https://bugs.winehq.org/show_bug.cgi?id=49098
# https://bugs.winehq.org/show_bug.cgi?id=49123
# https://bugs.winehq.org/show_bug.cgi?id=49041
if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor fd7992972b252ed262d33ef604e9e1235d2108c5 HEAD && ! git merge-base --is-ancestor 1f6423f778f7036a3875613e10b9c8c3b84584f0 HEAD ); then
  if [ "$_hotfixes_no_confirm" != "true" ] && [ "$_hotfixes_no_confirm" != "ignore" ]; then
    warning "Hotfix: An upstream patchset (starting with fd79929) breaks a large amount of games in various ways (ex: WoW, Overwatch, Star Citizen, Path of Exile etc.). As a temporary fix, this patch reverts it on current HEAD."
    read -rp "Apply it?"$'\n> N/y : ' _hotfixansw_fd79;
  fi
  if [[ "$_hotfixansw_fd79" =~ [yY] ]] || [ "$_hotfixes_no_confirm" = "true" ]; then
    if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor b7b1ad09629a6678383a5ae791a9507c9eb87be3 HEAD ); then
      _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/fd799297/fd7992972b252ed262d33ef604e9e1235d2108c5-6)
    elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor d2b70aa57a77103107a2e620999181c518d14bda HEAD ); then
      _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/fd799297/fd7992972b252ed262d33ef604e9e1235d2108c5-5)
    elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 68e675d73db4fb90fff84c0e1f6de3b492061b5f HEAD ); then
      _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/fd799297/fd7992972b252ed262d33ef604e9e1235d2108c5-4)
    elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 6f4272ce3e74f2d30f45bf0d407cdc9264b813a9 HEAD ); then
      _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/fd799297/fd7992972b252ed262d33ef604e9e1235d2108c5-3)
    elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 0a72ec1dacb59c72980c3133fddf316377349048 HEAD ); then
      _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/fd799297/fd7992972b252ed262d33ef604e9e1235d2108c5-2)
    else
      _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/fd799297/fd7992972b252ed262d33ef604e9e1235d2108c5)
    fi
  fi
fi
