#!/bin/bash

    # Joshua Ashton's take on making wine dialogs and menus less win95-ish - https://github.com/Joshua-Ashton/wine/tree/wine-better-theme
    if [ "$_use_josh_flat_theme" = "true" ]; then
      if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor fdf3015816168678c919ab282cf4e88704e931bc HEAD ); then
        _patchname='josh-flat-theme.patch' && _patchmsg="Add Josh's better-theme" && nonuser_patcher
      elif git merge-base --is-ancestor 6456973f0a64d326bb54da4675310caffc2588f1 HEAD && ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 0c249e6125fc9dc6ee86b4ef6ae0d9fa2fc6291b HEAD ); then
        _patchname='josh-flat-theme-fdf3015.patch' && _patchmsg="Add Josh's better-theme" && nonuser_patcher
      else
        _patchname='josh-flat-theme-6456973.patch' && _patchmsg="Add Josh's better-theme" && nonuser_patcher
      fi
    fi
