#!/bin/bash

# Frequent freezes with staging's ntdll-NtAlertThreadByThreadId patch - https://bugs.winehq.org/show_bug.cgi?id=50448#c15
# There is also a known perf regression which may or may not be improved by this hotfix
if [ "$_use_staging" = "true" ] && ( cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor dfddef9654d4a24642c61c287a93f22eb7a51e12 HEAD && ! git merge-base --is-ancestor f8ce6cbb21e09c80320514770c102a1a8e9cfde6 HEAD ) && [[ ! ${_staging_userargs[*]} =~ "ntdll-NtAlertThreadByThreadId" ]]; then
  warning "Hotfix: Fix for frequent freezes in some games with staging (when ntdll-NtAlertThreadByThreadId patch is enabled)"
  _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/dfddef96/zf_fix_dfddef96-1)
fi
