#!/bin/bash

	# Child window support for vk - Fixes World of Final Fantasy and others - https://bugs.winehq.org/show_bug.cgi?id=45277 - legacy (newer patchset from proton fshack applied later in the script for newer trees)
	if [ "$_childwindow_fix" = "true" ] && ! git merge-base --is-ancestor d318f43559dbb0093e22bab1aa0eb9dc01170cc2 HEAD; then
	  if ( [ "$_proton_fs_hack" != "true" ] && git merge-base --is-ancestor 0f972e2247932f255f131792724e4796b4b2b87a HEAD ) || ( ! git merge-base --is-ancestor 0f972e2247932f255f131792724e4796b4b2b87a HEAD ); then
	    if git merge-base --is-ancestor 011fabb2c43d13402ea18b6ea7be3669b5e6c7a8 HEAD; then
	      _staging_args+=(-W Pipelight -W winex11-Vulkan_support)
	      if git merge-base --is-ancestor c14de4c85e79563f5e859765d0015892ae925cd6 HEAD; then
	        _patchname='childwindow.patch' && _patchmsg="Applied child window for vk patch" && nonuser_patcher
	      elif git merge-base --is-ancestor bca1b7f2faeb0798f4af420c15ff5a1b1f7b40af HEAD; then
	        _patchname='childwindow-c14de4c.patch' && _patchmsg="Applied child window for vk patch" && nonuser_patcher
	      else
	        _patchname='childwindow-bca1b7f.patch' && _patchmsg="Applied child window for vk patch" && nonuser_patcher
	      fi
	    else
	      _patchname='childwindow-011fabb.patch' && _patchmsg="Applied child window for vk patch" && nonuser_patcher
	    fi
	  fi
	fi
