#!/bin/bash

	# Standalone child window support for vk - Fixes World of Final Fantasy and others - https://bugs.winehq.org/show_bug.cgi?id=45277 - legacy patchset for older trees applied at an earlier stage in the script
	if ( [ "$_childwindow_fix" = "true" ] && [ "$_proton_fs_hack" != "true" ] && [ "$_use_staging" = "true" ] ); then
	  if git merge-base --is-ancestor ad5cb8305f4ebc10992113f8f6a724d5f33a6bf8 HEAD; then
	    _patchname='childwindow-proton.patch' && _patchmsg="Applied child window for vk patch" && nonuser_patcher
	  elif git merge-base --is-ancestor c86955d3806879fc97b127730e9fb90e232710a7 HEAD; then
	    _patchname='childwindow-proton-ad5cb83.patch' && _patchmsg="Applied child window for vk patch" && nonuser_patcher
	  elif git merge-base --is-ancestor a25519ecc673c6c62d9fe606eeac249e4ac55140 HEAD; then
	    _patchname='childwindow-proton-c86955d.patch' && _patchmsg="Applied child window for vk patch" && nonuser_patcher
	  elif git merge-base --is-ancestor ef8e4b7e3e32e2beb317411c5bd6e5cedf71cfb7 HEAD; then
	    _patchname='childwindow-proton-a25519e.patch' && _patchmsg="Applied child window for vk patch" && nonuser_patcher
	  elif git merge-base --is-ancestor 83501c7eaabcff25373910b33b4e5c779b56f398 HEAD; then
	    _patchname='childwindow-proton-ef8e4b7.patch' && _patchmsg="Applied child window for vk patch" && nonuser_patcher
	  elif git merge-base --is-ancestor 262831bc63dca2d63171aa98d19e8f2566907dbc HEAD; then
	    _patchname='childwindow-proton-83501c7.patch' && _patchmsg="Applied child window for vk patch" && nonuser_patcher
	  elif git merge-base --is-ancestor 56b8a67f5af4aa68662a848715875fdb0b3d10d9 HEAD; then
	    _patchname='childwindow-proton-262831b.patch' && _patchmsg="Applied child window for vk patch" && nonuser_patcher
	  elif git merge-base --is-ancestor 3a11be1d48251ecbc0b99d7f4b3325bddbcd486b HEAD; then
	    _patchname='childwindow-proton-56b8a67.patch' && _patchmsg="Applied child window for vk patch" && nonuser_patcher
	  elif git merge-base --is-ancestor d318f43559dbb0093e22bab1aa0eb9dc01170cc2 HEAD; then
	    _patchname='childwindow-proton-3a11be1.patch' && _patchmsg="Applied child window for vk patch" && nonuser_patcher
	  fi
	fi

	if ( [ "$_childwindow_fix" = "true" ] && [ "$_proton_fs_hack" != "true" ] && [ "$_use_staging" = "true" ] ); then
	  if git merge-base --is-ancestor c86955d3806879fc97b127730e9fb90e232710a7 HEAD; then
	    if [ "$_protonify" = "true" ]; then
	       _patchname='OPWR-proton.patch' && _patchmsg="Applied other process window Vulkan rendering patchset" && nonuser_patcher
	    fi
	  fi
	fi
