#!/bin/bash

# legacy ntdll-WRITECOPY need for protonify
if [ "$_protonify" = "true" ] && [ "$_NOLIB32" != "wow64" ] && ( cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor 16dce521242b3f4a52cd2c8799ce6fe464fac83c HEAD ); then
  _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/legacy_ntdll_writecopy/legacy-ntdll-writecopy)
  if [ "$_use_staging" = "false" ]; then
    _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/legacy_ntdll_writecopy/additional-for-nonstaging)
  fi
  warning "Hotfix: Apply legacy ntdll-WRITECOPY for protonify patches"
fi
