#!/bin/bash

	# Add support for dxvk_config library to Wine's dxgi for Proton
	if ( [ "$_use_vkd3dlib" = "false" ] && [ "$_EXTERNAL_INSTALL" = "proton" ] && [ "$_protonify" = "true" ] && [ "$_unfrog" != "true" ] ) && git merge-base --is-ancestor 74dc0c5df9c3094352caedda8ebe14ed2dfd615e HEAD; then
	  if git merge-base --is-ancestor a71526bb07548ee0f45e03b12ab1048445000e05 HEAD; then
	    _patchname='dxvk_config_dxgi_support.patch' && _patchmsg="Add support for dxvk_config library to Wine's dxgi" && nonuser_patcher
	  elif git merge-base --is-ancestor 591068cec06257f3d5ed23e19ee4ad055ad978aa HEAD; then
	    _patchname='dxvk_config_dxgi_support-a71526b.patch' && _patchmsg="Add support for dxvk_config library to Wine's dxgi" && nonuser_patcher
	  else
	    _patchname='dxvk_config_dxgi_support-591068c.patch' && _patchmsg="Add support for dxvk_config library to Wine's dxgi" && nonuser_patcher
	  fi
	fi
