#!/bin/bash

# Sound regression - notably affecting Warframe - 370a538e to 6314a750
if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 6314a75006d1cfb86c1fb3da71be037fe646437c HEAD && ! git merge-base --is-ancestor db87636c91e5dca657150361fa9aabfe62ddf38c HEAD ); then
  warning "Hotfix: Fix Warframe and Ghostrunner sound on win10 prefixes."
  if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor fa6d22b976214ff4dfb32b431500b4cd1f7610a0 HEAD ); then
    _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/370a538e/xact-179-fixup)
  else
    _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/370a538e/xact-revert-179)
  fi
fi
