#!/bin/bash

	if [ "$_EXTERNAL_INSTALL" = "proton" ] && [ "$_unfrog" != "true" ]; then
	  source "$_where"/wine-tkg-patches/proton-tkg-specific/proton-staging/staging-winex11-key_translation
	  if [ "$_steamclient_noswap" != "true" ] && git merge-base --is-ancestor b7db0b52cee65a008f503ce727befcad3ba8d28a HEAD; then
	    if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor a14b4c7d0dbb9a200239070253d6590850654544 HEAD ); then
	      _patchname='proton-tkg-steamclient-swap.patch' && _patchmsg="Applied steamclient substitution hack" && nonuser_patcher
	    elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor a6bb3662dc484e7809e29308364438ea65cc7637 HEAD ); then
	      _patchname='proton-tkg-steamclient-swap-a14b4c7.patch' && _patchmsg="Applied steamclient substitution hack" && nonuser_patcher
	    elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor ae8562ed2277a5c051e131dc317e94aa3d5413c8 HEAD ); then
	      _patchname='proton-tkg-steamclient-swap-a6bb366.patch' && _patchmsg="Applied steamclient substitution hack" && nonuser_patcher
	    elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 4b65a7027f42a7c754f13e3639febb767fcf1780 HEAD ); then
	      _patchname='proton-tkg-steamclient-swap-ae8562e.patch' && _patchmsg="Applied steamclient substitution hack" && nonuser_patcher
	    elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 656edbb508d51cbe3155d856ee3f2c27a6cd4cba HEAD ); then
	      _patchname='proton-tkg-steamclient-swap-4b65a70.patch' && _patchmsg="Applied steamclient substitution hack" && nonuser_patcher
	    elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor d10410eac2b598699a3619d6e3f908e256af3afb HEAD ); then
	      _patchname='proton-tkg-steamclient-swap-656edbb.patch' && _patchmsg="Applied steamclient substitution hack" && nonuser_patcher
	    elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 1b9ada6cabd04ccb02c4ddcc82a53e62ea477948 HEAD ); then
	      _patchname='proton-tkg-steamclient-swap-d10410e.patch' && _patchmsg="Applied steamclient substitution hack" && nonuser_patcher
	    elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 72449b76e8e40f1690762545fd2c0021647da140 HEAD ); then
	      _patchname='proton-tkg-steamclient-swap-1b9ada6.patch' && _patchmsg="Applied steamclient substitution hack" && nonuser_patcher
	    elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 3190a5bcdd7fc043cf54ac070a5f602cb9dd140f HEAD ); then
	      _patchname='proton-tkg-steamclient-swap-72449b7.patch' && _patchmsg="Applied steamclient substitution hack" && nonuser_patcher
	    elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 5071a287437e624d2318a71218cb247522ac0d43 HEAD ); then
	      _patchname='proton-tkg-steamclient-swap-3190a5b.patch' && _patchmsg="Applied steamclient substitution hack" && nonuser_patcher
	    elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor b572cf30253b0922c7c476bfc666c0345eb50256 HEAD ); then
	      _patchname='proton-tkg-steamclient-swap-5071a28.patch' && _patchmsg="Applied steamclient substitution hack" && nonuser_patcher
	    elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor c2d84da8134cc9d07a114561c10c75bf91078370 HEAD ); then
	      _patchname='proton-tkg-steamclient-swap-b572cf3.patch' && _patchmsg="Applied steamclient substitution hack" && nonuser_patcher
	    elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 4ea07a30ce25e63ba61012ec9886ffc636e70bbb HEAD ); then
	      _patchname='proton-tkg-steamclient-swap-c2d84da.patch' && _patchmsg="Applied steamclient substitution hack" && nonuser_patcher
	    elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 0c249e6125fc9dc6ee86b4ef6ae0d9fa2fc6291b HEAD ); then
	      _patchname='proton-tkg-steamclient-swap-4ea07a3.patch' && _patchmsg="Applied steamclient substitution hack" && nonuser_patcher
	    elif git merge-base --is-ancestor 09db718d99026959c8bcf0718dccad589cad34f3 HEAD; then
	      _patchname='proton-tkg-steamclient-swap-de679af.patch' && _patchmsg="Applied steamclient substitution hack" && nonuser_patcher
	    else
	      _patchname='proton-tkg-steamclient-swap-09db718.patch' && _patchmsg="Applied steamclient substitution hack" && nonuser_patcher
	    fi
	  fi
	fi
