#!/bin/bash

# Fix for older than 7.14 trees crashing after a few seconds in game (7.0 minimum target)
if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor c7c729c0db7c3e246182a890de4c606f3e394d0e HEAD && ! git merge-base --is-ancestor 4bf9d2403f269e7f3595ad075a4afee9adbda51f HEAD ); then
  _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/ow2/c7c729c0)
fi

# https://gitlab.winehq.org/wine/wine/-/merge_requests/1148 - https://bugs.winehq.org/show_bug.cgi?id=53826
if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 4827ae13928259b22e48765be3f14aef5bc26146 HEAD ); then
  warning "Hotfix: Fixup for Battle.net failing with a Qt error"
  if [ "$_use_staging" = "true" ]; then
    _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/ow2/1148-staging)
  else
    _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/ow2/1148)
  fi
elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 74a5851ef48cafe02e4383df4dd5742ae55ba75f HEAD ); then
  warning "Hotfix: Fixup for Battle.net failing with a Qt error"
  if [ "$_use_staging" = "true" ]; then
    _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/ow2/1148-staging-4827ae1)
  else
    _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/ow2/1148-4827ae1)
  fi
elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 65797763b3ac4fcab7ffc83a4f95b2e87c81f58a HEAD ); then
  warning "Hotfix: Fixup for Battle.net failing with a Qt error"
  if [ "$_use_staging" = "true" ]; then
    _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/ow2/1148-staging-74a5851)
  else
    _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/ow2/1148-74a5851)
  fi
fi

# https://gitlab.winehq.org/wine/wine/-/merge_requests/1152
if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 079179fec720780679db3eed90adcc257f4ff240 HEAD && ! git merge-base --is-ancestor 8e9551f32435d76df87864147cc2119fd6555ef3 HEAD ); then
  warning "Hotfix: Fixup for Overwatch 2 crashing on 7.14+"
  _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/ow2/1152)
fi
