#!/bin/bash

# https://gitlab.winehq.org/wine/wine/-/merge_requests/1152
if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 079179fec720780679db3eed90adcc257f4ff240 HEAD ); then
  warning "Hotfix: Fixup for Overwatch 2 crashing on 7.14+"
  _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/ow2/1152)
fi
