#!/bin/bash

# https://gitlab.winehq.org/wine/wine/-/merge_requests/1148 - https://bugs.winehq.org/show_bug.cgi?id=53826
if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 65797763b3ac4fcab7ffc83a4f95b2e87c81f58a HEAD ); then
  warning "Hotfix: Fixup for Battle.net failing with a Qt error"
  if [ "$_use_staging" = "true" ]; then
    _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/ow2/1148-staging)
  else
    _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/ow2/1148)
  fi
fi

# https://gitlab.winehq.org/wine/wine/-/merge_requests/1152
if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 079179fec720780679db3eed90adcc257f4ff240 HEAD ); then
  warning "Hotfix: Fixup for Overwatch 2 crashing on 7.14+"
  _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/ow2/1152)
fi
