#!/bin/bash


	# Disable _steamvr_support on <=12d33d2
	if ( cd "${srcdir}"/"${_winesrcdir}" && ! git merge-base --is-ancestor 12d33d21d33788fd46898ea42e9592d33b6e7c8e HEAD ); then
	  _steamvr_support="false"
	  _proton_branch_exp="DENIED"
	else
	  _steamvr_support="true"
	  _proton_branch_exp="true"
	fi

	  if [ "$_steamvr_support" = "true" ] && [ "$_unfrog" != "true" ]; then
	    if [ "$_proton_fs_hack" = "true" ] && [ "$_use_staging" = "true" ] && git merge-base --is-ancestor 656edbb508d51cbe3155d856ee3f2c27a6cd4cba HEAD; then
	      if [ "$_shared_gpu_resources" = "true" ]; then
	        if git merge-base --is-ancestor c86955d3806879fc97b127730e9fb90e232710a7 HEAD; then
	          _patchname='proton-vr-fshack-shared-gpu-resources.patch' && _patchmsg="Enable Proton vr-related wined3d additions" && nonuser_patcher
	        fi
	      else
	        if git merge-base --is-ancestor 7d20333faf8e93a3a16680cf1beadc9cdcb50c45 HEAD; then
	          _patchname='proton-vr-fshack.patch' && _patchmsg="Enable Proton vr-related wined3d additions" && nonuser_patcher
	        elif git merge-base --is-ancestor 872dc83e81c942d17a39700c4b520a6e92ddbdf2 HEAD; then
	          _patchname='proton-vr-fshack-7d20333.patch' && _patchmsg="Enable Proton vr-related wined3d additions" && nonuser_patcher
	        elif git merge-base --is-ancestor f6f66661b3fabdcd6cf2f4999b3029e72d492fa4 HEAD; then
	          _patchname='proton-vr-fshack-872dc83.patch' && _patchmsg="Enable Proton vr-related wined3d additions" && nonuser_patcher
	        elif git merge-base --is-ancestor 9b220b8079f882cca80351ec5ee1dd8c153d1950 HEAD; then
	          _patchname='proton-vr-fshack-f6f6666.patch' && _patchmsg="Enable Proton vr-related wined3d additions" && nonuser_patcher
	        elif git merge-base --is-ancestor cb4385ea8732df1f3dcc764ced984a45adbbf875 HEAD; then
	          _patchname='proton-vr-fshack-9b220b8.patch' && _patchmsg="Enable Proton vr-related wined3d additions" && nonuser_patcher
	        elif git merge-base --is-ancestor 5d62e5603a3d4c665c129b8f715407c9edece839 HEAD; then
	          _patchname='proton-vr-fshack-cb4385e.patch' && _patchmsg="Enable Proton vr-related wined3d additions" && nonuser_patcher
	        elif git merge-base --is-ancestor 656edbb508d51cbe3155d856ee3f2c27a6cd4cba HEAD; then
	          _patchname='proton-vr-fshack-5d62e56.patch' && _patchmsg="Enable Proton vr-related wined3d additions" && nonuser_patcher
	        fi
	      fi
	    else
	      if git merge-base --is-ancestor c065b4fe0b3622e0c737a4c7c1c514273ad2d8a7 HEAD; then
	        _patchname='proton-vr.patch' && _patchmsg="Enable Proton vr-related wined3d additions" && nonuser_patcher
	      elif git merge-base --is-ancestor 4413e94908bfd561c759b121a7f460b51677cf0b HEAD; then
	        _patchname='proton-vr-c065b4f.patch' && _patchmsg="Enable Proton vr-related wined3d additions" && nonuser_patcher
	      elif git merge-base --is-ancestor 890877f14574e45b5b30d9bcc93d30842b7d0065 HEAD; then
	        _patchname='proton-vr-4413e94.patch' && _patchmsg="Enable Proton vr-related wined3d additions" && nonuser_patcher
	      elif git merge-base --is-ancestor 7d20333faf8e93a3a16680cf1beadc9cdcb50c45 HEAD; then
	        _patchname='proton-vr-890877f.patch' && _patchmsg="Enable Proton vr-related wined3d additions" && nonuser_patcher
	      elif git merge-base --is-ancestor 872dc83e81c942d17a39700c4b520a6e92ddbdf2 HEAD; then
	        _patchname='proton-vr-7d20333.patch' && _patchmsg="Enable Proton vr-related wined3d additions" && nonuser_patcher
	      elif git merge-base --is-ancestor f6f66661b3fabdcd6cf2f4999b3029e72d492fa4 HEAD; then
	        _patchname='proton-vr-872dc83.patch' && _patchmsg="Enable Proton vr-related wined3d additions" && nonuser_patcher
	      elif git merge-base --is-ancestor 9b220b8079f882cca80351ec5ee1dd8c153d1950 HEAD; then
	        _patchname='proton-vr-f6f6666.patch' && _patchmsg="Enable Proton vr-related wined3d additions" && nonuser_patcher
	      elif git merge-base --is-ancestor cb4385ea8732df1f3dcc764ced984a45adbbf875 HEAD; then
	        _patchname='proton-vr-9b220b8.patch' && _patchmsg="Enable Proton vr-related wined3d additions" && nonuser_patcher
	      elif git merge-base --is-ancestor 5d62e5603a3d4c665c129b8f715407c9edece839 HEAD; then
	        _patchname='proton-vr-cb4385e.patch' && _patchmsg="Enable Proton vr-related wined3d additions" && nonuser_patcher
	      elif git merge-base --is-ancestor 831ff102008e2ba93a403344646b5ed67258eaeb HEAD; then
	        _patchname='proton-vr-656edbb.patch' && _patchmsg="Enable Proton vr-related wined3d additions" && nonuser_patcher
	      elif git merge-base --is-ancestor 12d33d21d33788fd46898ea42e9592d33b6e7c8e HEAD; then # 6.12
	        _patchname='proton-vr-831ff10.patch' && _patchmsg="Enable Proton vr-related wined3d additions" && nonuser_patcher
	      elif git merge-base --is-ancestor bff6bc6a79ffc3a915219a6dfe64c9bcabaaeceb HEAD && [ "$_proton_fs_hack" = "true" ]; then
	        _patchname='proton-vr-12d33d2.patch' && _patchmsg="Enable Proton vr-related wined3d additions" && nonuser_patcher
	      elif git merge-base --is-ancestor e447e86ae2fbfbd9dee1b488e38a653aaea5447e HEAD && [ "$_proton_fs_hack" = "true" ]; then
	        _patchname='proton-vr-bff6bc6.patch' && _patchmsg="Enable Proton vr-related wined3d additions" && nonuser_patcher
	      elif git merge-base --is-ancestor a6d74b0545afcbf05d53fcbc9641ecc36c3be95c HEAD && [ "$_proton_fs_hack" = "true" ]; then
	        _patchname='proton-vr-e447e86.patch' && _patchmsg="Enable Proton vr-related wined3d additions" && nonuser_patcher
	      elif git merge-base --is-ancestor c736321633c6a247b406be50b1780ca0439ef8b0 HEAD && [ "$_proton_fs_hack" = "true" ]; then
	        _patchname='proton-vr-a6d74b.patch' && _patchmsg="Enable Proton vr-related wined3d additions (<a6d74b)" && nonuser_patcher
	      elif [ "$_proton_fs_hack" = "true" ]; then
	        _patchname='proton-vr-c736321.patch' && _patchmsg="Enable Proton vr-related wined3d additions (<c736321)" && nonuser_patcher
	      fi
	    fi
	  fi
