#!/bin/bash

# Add Rémi's pending fixes for hidclass - https://source.winehq.org/patches/data/215195 - https://source.winehq.org/patches/data/215197
if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor afd63fa6a75cfabac450c42a3e9ccd78596b7728 HEAD && ! git merge-base --is-ancestor 9421dd2b3cd7114bf390c3ffcec30ab4bc95b7ef HEAD ); then
  warning "Hotfix: Add Rémi's fixes for gamepad handling on 6.18 release"
  _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/hid_Remi_6.18release/215195)
  _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/hid_Remi_6.18release/215197)
fi
