#!/bin/bash

# Fix regression of login issue in Guild Wars 1 and Guild Wars 2 - https://bugs.winehq.org/show_bug.cgi?id=52429
if ( [ "$_use_staging" = "true" ] && [ "$_proton_fs_hack" != "true" ] || [ "$_use_staging" = "false" ] ) && ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 1e35966eb57db7060d0c459bc7aaac2f6cad7442 HEAD && ! git merge-base --is-ancestor 7b51216198237c04a8994cda1bdb45fdb4482b32 HEAD ); then
  warning "Workaround for Guild Wars 1 and Guild Wars 2 can't login on 7.14"
  _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/1e35966/gofman_hotfix)
fi

