#!/bin/bash

# bcrypt fixes for RDR2
if [ "$_use_staging" = "true" ] && ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 2ad44002da683634de768dbe49a0ba09c5f26f08 HEAD ); then
  warning "Hotfix: Bcrypt fixes for RDR2"
  if [ "$_proton_bcrypt" = "true" ] && ( cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor 37e000145f07c4ec6f48fdac5969bbbb05435d52 HEAD ) && grep -Fxq 'Disabled: true' "${srcdir}/${_stgsrcdir}/patches/bcrypt-ECDHSecretAgreement/definition"; then
    if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor ef6e33f89f94e1fc109bb6c415d7c80f141619d5 HEAD ); then
      _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/rdr2/ef6e33f)
    else
      _hotfix_mainlinereverts+=(341cb1a933aec7b2858414f571ea98ba29caa72a)
    fi
    _hotfix_mainlinereverts+=(dd61c5638a0e597a488ca74e48f1ac97bc008f93 48075d2a0874d368e617632bd5e875e4bc18c411 1fa5bfd7dab270113c8fd2b48c838396719c639b 5b860a44a0051cf779ec3391610a807e711d184f 00dfa1bd04ae7f93ee7dd4235dd2439697efd318 777cbf06d2e8db298313982b7823acbc40dc05db b352d353b41654ad2b94d46747c5d203acc417f3 0c2408464cfea0d3e5b073c56ac0d264d1abe576 c1ed9ca9b18267b2139fcf7fd68f24d2c6d7a2a3 9176251af425ba494c0334c5659aa47941ee7c85 f3d4df60ff4afbf1983387a098ae96830384f53a)
    if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 194e09baeca42b369b391d87c9605338b8fbc978 HEAD ); then
      _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/rdr2/0001-proton-bcrypt_rdr2_fixes5)
    elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 045f50a78a210cc16e25ebffa276003ae69e1994 HEAD ); then
      _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/rdr2/0001-proton-bcrypt_rdr2_fixes4)
    elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor ab4edfd8621d4811ce9a74d066eef0904a45a74f HEAD ); then
      _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/rdr2/0001-proton-bcrypt_rdr2_fixes3)
    elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor fcc827d141f32954545b349f06b01a3909b95ac0 HEAD ); then
      _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/rdr2/0001-proton-bcrypt_rdr2_fixes2)
    else
      _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/rdr2/0001-proton-bcrypt_rdr2_fixes)
    fi
    _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/rdr2/0002-bcrypt-Add-support-for-calculating-secret-ecc-keys)
    if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 39336fd02d90b8d7d1d24d5eb31f9b0172b60a17 HEAD ); then
      _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/rdr2/0003-bcrypt-Add-support-for-OAEP-padded-asymmetric-key-de2)
    else
      _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/rdr2/0003-bcrypt-Add-support-for-OAEP-padded-asymmetric-key-de)
    fi
  fi
fi
