#!/bin/bash

	if [ "$_EXTERNAL_INSTALL" = "proton" ] && [ "$_unfrog" != "true" ] && ! git merge-base --is-ancestor 74dc0c5df9c3094352caedda8ebe14ed2dfd615e HEAD || ([ "$_protonify" = "true" ] && git merge-base --is-ancestor 74dc0c5df9c3094352caedda8ebe14ed2dfd615e HEAD); then
	  if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 7a054a4a8f477142d88c5ec07e0ba32ab52875c9 HEAD ); then
	    if [ "$_use_staging" = "true" ]; then
	      if ! git merge-base --is-ancestor dedd5ccc88547529ffb1101045602aed59fa0170 HEAD; then
	        _patchname='proton-tkg-staging-rpc.patch' && _patchmsg="Using Steam-specific Proton-tkg patches (staging) 1/3" && nonuser_patcher
	      fi
	      if [ "$_use_fsync" = "false" ]; then
	        _patchname='proton-tkg-staging-nofsync.patch' && _patchmsg="Using Steam-specific Proton-tkg patches (staging) 2/3" && nonuser_patcher
		  else
	        _patchname='proton-tkg-staging.patch' && _patchmsg="Using Steam-specific Proton-tkg patches (staging) 2/3" && nonuser_patcher
		  fi
	      if [ "$_EXTERNAL_INSTALL" = "proton" ] && [ "$_unfrog" != "true" ]; then
	        source "$_where"/wine-tkg-patches/proton-tkg-specific/proton-steam-bits/proton-steam-bits
	        source "$_where"/wine-tkg-patches/proton-tkg-specific/proton-seccomp-envvar/proton-seccomp-envvar
	      fi
	    else
	      if ! git merge-base --is-ancestor dedd5ccc88547529ffb1101045602aed59fa0170 HEAD; then
	        _patchname='proton-tkg-rpc.patch' && _patchmsg="Using Steam-specific Proton-tkg patches 1/3" && nonuser_patcher
	      fi
	      _patchname='proton-tkg.patch' && _patchmsg="Using Steam-specific Proton-tkg patches 2/3" && nonuser_patcher
	      if [ "$_EXTERNAL_INSTALL" = "proton" ] && [ "$_unfrog" != "true" ]; then
	        source "$_where"/wine-tkg-patches/proton-tkg-specific/proton-steam-bits/proton-steam-bits
	      fi
	    fi
	  else
	    if git merge-base --is-ancestor fbfc8df4bb0bedff6832c55a3db10f5e239d99af HEAD; then
	      _lastcommit="7a054a4a"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor ba50573f91912ba30651501c1f32dc466f0030cb HEAD; then
	      _lastcommit="fbfc8df"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor ca89965a2e87ca842a65f76e99b1d1db6c345e8a HEAD; then
	      _lastcommit="ba50573"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor ea890c4733db5119fdb63b900bb7e5c8d04b5245 HEAD; then
	      _lastcommit="ca89965"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 643538a836f33b4996730cf05dc2af77667d6150 HEAD; then
	      _lastcommit="ea890c4"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 3681a68e7804e0398b3f15f16af4ae19ef2e5dba HEAD; then
	      _lastcommit="643538a"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 7c26c458588b629be8dbff4e4b22459cf8206108 HEAD; then
	      _lastcommit="3681a68"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 48e6bf3cf1aabdd2ac640f572416b9169e324f21 HEAD; then
	      _lastcommit="7c26c45"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor c14de4c85e79563f5e859765d0015892ae925cd6 HEAD; then
	      _lastcommit="48e6bf3"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor f2371a8b47cebdc497ec1c4e3d292c0de16df8cd HEAD; then
	      _lastcommit="c14de4c"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 59485f00c917061c097c1805d7fa7f61c380c749 HEAD; then
	      _lastcommit="f2371a8"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 2369657333cb99d395f6852c07feddb05ee93ae5 HEAD; then
	      _lastcommit="59485f0"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 7ccb5df0fcfbfdd052fe6032979fb731da2648a9 HEAD; then
	      _lastcommit="2369657"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 828304dab301a733c7b1a6f53c8bd0681fbae6c4 HEAD; then
	      _lastcommit="7ccb5df"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 161f1b7b6f0c21d46900176fa3890240805980c4 HEAD; then
	      _lastcommit="828304d"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor e9003720d6d96e4489452c59c21d967c71bb4338 HEAD; then
	      _lastcommit="161f1b7"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor b4280a486f7308fd1da260cd5b48b7d9e3c747c5 HEAD; then
	      _lastcommit="e900372"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 8c5cf9ce16dbedfb2b2e4d3338cf3ea9dc2b1427 HEAD; then
	      _lastcommit="b4280a4"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor af902c188ebaf7d6dda3b628409d8c390ab410d5 HEAD; then
	      _lastcommit="8c5cf9c"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor ddc9ef10c9de1ff8885db312f013a069dee21933 HEAD; then
	      _lastcommit="af902c1"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 871f333d55c2c472014a861bfdd256c1f497dd40 HEAD; then
	      _lastcommit="ddc9ef1"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 9e8fbdab722c9af1feec3f393a6303e69ce91edb HEAD; then
	      _lastcommit="871f333"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 863858da2aa42edfa3b4e639905fcad7056eaeb5 HEAD; then
	      _lastcommit="9e8fbda"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor fae940df23a8905b8852be9c10019cbe0e89f1c2 HEAD; then
	      _lastcommit="863858d"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 2f41d8511882253c6f3c2b031255173b40416b29 HEAD; then
	      _lastcommit="fae940d"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 5574c22d548de6e78e36ee1e5b6a5ba8229f416c HEAD; then
	      _lastcommit="2f41d85"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 24d791e2e9792a28a18414710aee34c255b10c67 HEAD; then
	      _lastcommit="5574c22"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor fded20df6c7422e85dbcd5a20475fd0c5d38d3c6 HEAD; then # staging 769ddd9f009d8b209e840a8d32bb05f43cbe4295
	      _lastcommit="24d791e"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor fefe108e2043d8a9d993b4e2cb129c851ca5e795 HEAD; then
	      _lastcommit="fded20d"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 8dd04c77cb3f1f24833f002499bf6299da38dcd6 HEAD; then
	      _lastcommit="fefe108"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor dfd5f109fb4ebad859bf3ce3960b3b2b2ad1341d HEAD; then
	      _lastcommit="8dd04c7"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 22fa68bbd9c1f7e616f5c8845a33ba78346ef0a4 HEAD; then
	      _lastcommit="dfd5f10"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 7ba3c31d84fcf49810aaf78aff63ef28b32eb159 HEAD; then
	      _lastcommit="22fa68b"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor ee2ef012f7466f6dcada1e8fe40da5132d4f1bb6 HEAD; then
	      _lastcommit="7ba3c31"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 36ac0c1cfbd298bb8d82a465c00adacdb387599c HEAD; then
	      _lastcommit="ee2ef01"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 6b8cbfe3fdc1ab8c6efd55dc51df7c3d738c4a47 HEAD; then
	      _lastcommit="36ac0c1"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 0c6d042cc3b1b2cbfb702bb3d199cc7a83e6cbd2 HEAD; then
	      _lastcommit="6b8cbfe"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor bf8c5afef1b3636266bbd2ca686cbebff4d7a849 HEAD; then
	      _lastcommit="0c6d042"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 656edbb508d51cbe3155d856ee3f2c27a6cd4cba HEAD; then
	      _lastcommit="bf8c5af"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 8714eb2fef7182a9c73b9963493935decca89fdc HEAD; then
	      _lastcommit="656edbb"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor ae5ebeaff9f73bf4c006dead20d3cb84327c7234 HEAD; then
	      _lastcommit="8714eb2"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 86bc819f07a67dc5ef2cb5bc9f8d609daa0f7b64 HEAD; then
	      _lastcommit="ae5ebea"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 96aa7bcd7b86fa9ebb2460f14122913365ec5b09 HEAD; then
	      _lastcommit="86bc819"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 488a00c3be2e4ef0dd0c945ac96e0f1a49c449f8 HEAD; then
	      _lastcommit="96aa7bc"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 37be0989540cf84dd9336576577ae535f2b6bbb8 HEAD; then
	      _lastcommit="488a00c"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor a34e8c2bc36bf28b3c1b7ffeac21c95c39596418 HEAD; then
	      _lastcommit="37be098"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 548bc54bf396d74b5b928bf9be835272ddda1886 HEAD; then
	      _lastcommit="a34e8c2"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 850083d088b831b5ce59393d06c9d2f6fc5200a6 HEAD; then
	      _lastcommit="548bc54"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor e843605b238a754c819f0a1f80242ee7f35deda1 HEAD; then
	      _lastcommit="850083d"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor d8be85863fedf6982944d06ebd1ce5904cb3d4e1 HEAD; then
	      _lastcommit="e843605"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor e7b0b35d57d3567d6b6891beaf3241179a926ad6 HEAD; then
	      _lastcommit="d8be858"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor b7fafabc77b58fb33a5a543d423232f18f9d5f05 HEAD; then
	      _lastcommit="e7b0b35"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 72449b76e8e40f1690762545fd2c0021647da140 HEAD; then
	      _lastcommit="b7fafab"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 6ba7773121fd3b65e48ba65b49e742ab9b061210 HEAD; then
	      _lastcommit="72449b7"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 7b17d7081512db52ef852705445762ac4016c29f HEAD; then
	      _lastcommit="6ba7773"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor d94d1a8b263a020575bf8dd76509d9e603434095 HEAD; then
	      _lastcommit="7b17d70"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 847db3c1d3f5444808814cbea8f2920b16a96fcb HEAD; then
	      _lastcommit="d94d1a8"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor d127a14a7f1941539753f029fb52f407514b1106 HEAD; then
	      _lastcommit="847db3c"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor d327527cec22c1123781e6c5a637032a31698b91 HEAD; then
	      _lastcommit="d127a14"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor e58405000c6037d9d281ec06a87bf72c5fc79866 HEAD; then
	      _lastcommit="d327527"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 20fff538c49c87abffd583f6b63371592ebdd835 HEAD; then
	      _lastcommit="e584050"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 5c009c17b3a212c3f5b0034c465077c0c593daae HEAD; then
	      _lastcommit="20fff53"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 0986c8a35fdf9e1070390e0a424042f8396b6932 HEAD; then
	      _lastcommit="5c009c1"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 21f5597de417575d476a00b567d972a89903b4b6 HEAD; then
	      _lastcommit="0986c8a"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 8c0ced87bcec8bdc505bf844cc9247106ebd8c36 HEAD; then
	      _lastcommit="21f5597"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor ec9f3119306e34f5a8bd3bfeb233eed740c1c6ae HEAD; then
	      _lastcommit="8c0ced8"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 5d82baf9747b7b133cad3be77c0cc9e24cc09582 HEAD; then
	      _lastcommit="ec9f311"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 02e3327f0687559486739f7da7b602c2baae070a HEAD; then
	      _lastcommit="5d82baf"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 96abde9eac97dc0fa5ff6ec8176e51cc3673fb44 HEAD; then
	      _lastcommit="02e3327"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 72c562ce9c481e73a01f50e17b624095aab11bdc HEAD; then
	      _lastcommit="96abde9"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 11daf1869078a60ed2588ff5a61a4d9b27985beb HEAD; then
	      _lastcommit="72c562c"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 7ef35b33936682c01f1c825b7d1b07567a691c12 HEAD; then
	      _lastcommit="11daf18"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 90024e492dcefd204c6c953a804c0d51544db5b2 HEAD; then
	      _lastcommit="7ef35b3"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor a24bdfc2c69c5648cbb3df762149b2647e209a09 HEAD; then
	      _lastcommit="90024e4"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 2cb4bdb10abcfd751d4d1b2ca7780c778166608a HEAD; then
	      _lastcommit="a24bdfc"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor e51ae86937c547124c906fb1d5db7a142af60686 HEAD; then
	      _lastcommit="2cb4bdb"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 65cff869513f8f66655b602ab2bc62e1c3b69c51 HEAD; then
	      _lastcommit="e51ae86"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 8abcae547501809d1cbf01b14669707c0bd66714 HEAD; then
	      _lastcommit="65cff86"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 10dde32dc6c530d755f68a6edfb50d21c6edd2a8 HEAD; then
	      _lastcommit="8abcae5"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 26ee9134d5d75ee515ccf06987cd024b64e498aa HEAD; then
	      _lastcommit="10dde32"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 50798b1320b24e7c74d350853a895b16881c376d HEAD; then
	      _lastcommit="26ee913"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 0027827290f4a411389e402eb2e1766d94e5e0c1 HEAD; then
	      _lastcommit="50798b1"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor c6d85fc2178094840a5ea2cd4823c7b68e48e473 HEAD; then
	      _lastcommit="0027827"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor d4bb0c4639aea2e8df80e577bd20b7f51c033e33 HEAD; then
	      _lastcommit="c6d85fc"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 6f158754435f403864052e595ab627dadac2666f HEAD; then
	      _lastcommit="d4bb0c4"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 251262a44a8f8403fd963e7bb510da778944af1b HEAD; then
	      _lastcommit="6f15875"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 447924a6d68f7919bd451661314a52aa99cab709 HEAD; then
	      _lastcommit="251262a"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 60f11d2929629f0da257b810936f0239ad895596 HEAD; then
	      _lastcommit="447924a"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 1f3064c5d5ac851c6fdfb85bc8ff5ea046f32acc HEAD; then
	      _lastcommit="60f11d2"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 89698cfae4d9aefd3f77c2982e64f7b98e00edf1 HEAD; then
	      _lastcommit="1f3064c"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 0c249e6125fc9dc6ee86b4ef6ae0d9fa2fc6291b HEAD; then
	      _lastcommit="89698cf"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 1ec8bf9b739f1528b742169670eac2350b33a7d4 HEAD; then
	      _lastcommit="de679af"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 7d67c412ead12a9db963ff74977f4a63f5d02aa9 HEAD; then
	      _lastcommit="1ec8bf9"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor d17b118f030407a973a4aaaab58774449a6235cc HEAD; then
	      _lastcommit="7d67c41"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor d806203850c9666ff32637f5215fbb21a0f2bc9c HEAD; then
	      _lastcommit="d17b118"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor d93137e2e07e0fea56e0c5148c27b1c7e9cb5a65 HEAD; then
	      _lastcommit="d806203"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 8898a6951988c95db3e92146b948a3b2aed08fd2 HEAD; then
	      _lastcommit="d93137e"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 0556d9e6f1c0951e6e4026efe3b176407b82fc7b HEAD; then
	      _lastcommit="8898a69"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor a302ab44acaf72ecc9b0307c82a7d11f759e6a72 HEAD; then
	      _lastcommit="0556d9e"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 2633a5c1ae542f08f127ba737fa59fb03ed6180b HEAD; then
	      _lastcommit="a302ab4"
	      _rpc="1"
	      _stmbits="1"
	    elif ( cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor d33cdb84fd8fed24e3a9ce89954ad43213b86426 HEAD ); then
	      _lastcommit="2633a5c"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor dedd5ccc88547529ffb1101045602aed59fa0170 HEAD; then
	      _lastcommit="d33cdb8"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 7f9eb22af8c3c8f9a0d8e07b0e6d8ee89feacd9e HEAD; then
	      _lastcommit="dedd5cc"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor bbf2836a85046bf9af2dca3b3158250d79302324 HEAD; then
	      _lastcommit="7f9eb22"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor b87256cd1db21a59484248a193b6ad12ca2853ca HEAD; then
	      _lastcommit="bbf2836"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 120505ed6b590daea11486a512dd563600d0329f HEAD; then
	      _lastcommit="b87256c"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 9d38c4864c4800313812feef2c3bc6ca6551ce57 HEAD; then
	      _lastcommit="120505e"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 14df0183b0b43049d0f645f72f435309cb6836a4 HEAD; then
	      _lastcommit="9d38c48"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 56a6bc87acbbbee74fb6cd8e77ae61828e274c2d HEAD; then
	      _lastcommit="14df018"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 50aeb5e777d9a8836f5530755afab10e042c623f HEAD; then
	      _lastcommit="56a6bc8"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 74dc0c5df9c3094352caedda8ebe14ed2dfd615e HEAD; then
	      _lastcommit="50aeb5e"
	      _rpc="1"
	      _stmbits="1"
	    elif git merge-base --is-ancestor 2aad95254c19df21fc0f7c4413ca3874c8d87997 HEAD; then
	      _lastcommit="74dc0c5"
	      _rpc="1"
	    elif git merge-base --is-ancestor 8000b5415d2c249176bda3d8b49f8fc9978e1623 HEAD; then
	      _lastcommit="2aad952"
	      _rpc="1"
	    elif git merge-base --is-ancestor 51ffea5a3940bdc74b44b9303c4574dfb156efc0 HEAD; then
	      _lastcommit="8000b54"
	      _rpc="1"
	    elif git merge-base --is-ancestor 477ff7e034e882cf0dc24aa0b459ec957608a1c3 HEAD; then
	      _lastcommit="51ffea5"
	      _rpc="1"
	    elif git merge-base --is-ancestor aa827393311987319998a5dc1860e4696d495114 HEAD; then
	      _lastcommit="477ff7e"
	      _rpc="1"
	    elif git merge-base --is-ancestor b7db0b52cee65a008f503ce727befcad3ba8d28a HEAD; then
	      _lastcommit="aa82739"
	      _rpc="1"
	    elif git merge-base --is-ancestor 6d7828e8df68178ca662bc618f7598254afcfbe1 HEAD; then
	      _lastcommit="b7db0b5"
	      _rpc="1"
	    elif git merge-base --is-ancestor 8d25965e12717b266f2fc74bb10d915234d16772 HEAD; then
	      _lastcommit="6d7828e"
	      _rpc="1"
	    elif git merge-base --is-ancestor 619bd16e7a7486ca72cde1df01791629efb61341 HEAD; then
	      _lastcommit="8d25965"
	      _rpc="1"
	    elif git merge-base --is-ancestor 940c3b4896a75b65351d4c7d610f1071d0c9d0be HEAD; then
	      _lastcommit="619bd16"
	      _rpc="1"
	    elif git merge-base --is-ancestor 0bebbbaa51c7647389ef9ac886169f6037356460 HEAD; then
	      _lastcommit="940c3b4"
	    elif git merge-base --is-ancestor 05d00276c627753487c571c30fddfc56c02ad37e HEAD; then
	      _lastcommit="0bebbba"
	    elif git merge-base --is-ancestor 09f588ee6909369b541398dd392d3ff77231e6a6 HEAD; then
	      _lastcommit="05d0027"
	    elif git merge-base --is-ancestor 0116660dd80b38da8201e2156adade67fc2ae823 HEAD; then
	      _lastcommit="09f588e"
	    elif git merge-base --is-ancestor eafb4aff5a2c322f4f156fdfada5743834996be4 HEAD; then
	      _lastcommit="0116660"
	    else
	      _lastcommit="eafb4af"
        fi
	    if [ "$_use_staging" = "true" ]; then
	      if ! git merge-base --is-ancestor dedd5ccc88547529ffb1101045602aed59fa0170 HEAD && [ "$_rpc" = "1" ]; then
	        _patchname='proton-tkg-staging-rpc.patch' && _patchmsg="Using Steam-specific Proton-tkg patches (staging) 1/2" && nonuser_patcher
	      fi
	      if [ "$_use_fsync" = "false" ]; then
	        _patchname="proton-tkg-staging-nofsync-$_lastcommit.patch" && _patchmsg="Using Steam-specific Proton-tkg patches (staging-$_lastcommit) 2/2" && nonuser_patcher
	      else
	        _patchname="proton-tkg-staging-$_lastcommit.patch" && _patchmsg="Using Steam-specific Proton-tkg patches (staging-$_lastcommit) 2/2" && nonuser_patcher
	      fi
	      if [ "$_stmbits" = "1" ] && [ "$_EXTERNAL_INSTALL" = "proton" ] && [ "$_unfrog" != "true" ]; then
	        source "$_where"/wine-tkg-patches/proton-tkg-specific/proton-steam-bits/proton-steam-bits
	        source "$_where"/wine-tkg-patches/proton-tkg-specific/proton-seccomp-envvar/proton-seccomp-envvar
	      fi
	    else
	      if ! git merge-base --is-ancestor dedd5ccc88547529ffb1101045602aed59fa0170 HEAD && [ "$_rpc" = "1" ]; then
	        _patchname='proton-tkg-rpc.patch' && _patchmsg="Using Steam-specific Proton-tkg patches 1/2" && nonuser_patcher
	      fi
	      _patchname="proton-tkg-$_lastcommit.patch" && _patchmsg="Using Steam-specific Proton-tkg patches ($_lastcommit) 2/2" && nonuser_patcher
	      if [ "$_stmbits" = "1" ] && [ "$_EXTERNAL_INSTALL" = "proton" ] && [ "$_unfrog" != "true" ]; then
	        source "$_where"/wine-tkg-patches/proton-tkg-specific/proton-steam-bits/proton-steam-bits
	      fi
	    fi
	  fi
	  if [ "$_proton_fs_hack" != "true" ] && [ "$_wayland_driver" != "true" ] && [ "$_use_staging" = "true" ] && [ "$_childwindow_fix" = "true" ] && git merge-base --is-ancestor 3ded60bd1654dc689d24a23305f4a93acce3a6f2 HEAD; then
	    if git merge-base --is-ancestor 5d860f62f6cb70a8f3b1b8ca0a9471ab1da56c36 HEAD; then
	      _patchname='proton-tkg-additions.patch' && _patchmsg="Using additional Proton-tkg patches" && nonuser_patcher
	    elif git merge-base --is-ancestor 48e6bf3cf1aabdd2ac640f572416b9169e324f21 HEAD; then
	      _patchname='proton-tkg-additions-5d860f.patch' && _patchmsg="Using additional Proton-tkg patches" && nonuser_patcher
	    elif git merge-base --is-ancestor 3c9423618673702ab7a3129f0ca61a0605adab35 HEAD; then
	      _patchname='proton-tkg-additions-48e6bf3.patch' && _patchmsg="Using additional Proton-tkg patches" && nonuser_patcher
	    elif git merge-base --is-ancestor 2bfe81e41f93ce75139e3a6a2d0b68eb2dcb8fa6 HEAD; then
	      _patchname='proton-tkg-additions-3c94236.patch' && _patchmsg="Using additional Proton-tkg patches" && nonuser_patcher
	    elif git merge-base --is-ancestor 70c9239cb2eef696eea109f3f8e7a58f80cd3823 HEAD; then
	      _patchname='proton-tkg-additions-2bfe81e.patch' && _patchmsg="Using additional Proton-tkg patches" && nonuser_patcher
	    elif git merge-base --is-ancestor 19d2dc0dfc22d0fc1255a462be6494906b9bd3e8 HEAD; then
	      _patchname='proton-tkg-additions-ad5cb83.patch' && _patchmsg="Using additional Proton-tkg patches" && nonuser_patcher
	    elif git merge-base --is-ancestor 6bf3b5539a3be40ed60cada89204685566c141a0 HEAD; then
	      _patchname='proton-tkg-additions-19d2dc0.patch' && _patchmsg="Using additional Proton-tkg patches" && nonuser_patcher
	    elif git merge-base --is-ancestor 1f90d03b7888f902d2aa6101bd60aa47766071cd HEAD; then
	      _patchname='proton-tkg-additions-6bf3b55.patch' && _patchmsg="Using additional Proton-tkg patches" && nonuser_patcher
	    elif git merge-base --is-ancestor af902c188ebaf7d6dda3b628409d8c390ab410d5 HEAD; then
	      _patchname='proton-tkg-additions-1f90d03.patch' && _patchmsg="Using additional Proton-tkg patches" && nonuser_patcher
	    elif git merge-base --is-ancestor ad5cb8305f4ebc10992113f8f6a724d5f33a6bf8 HEAD; then
	      _patchname='proton-tkg-additions-af902c1.patch' && _patchmsg="Using additional Proton-tkg patches" && nonuser_patcher
	    elif git merge-base --is-ancestor 6be2138da66db5d1a11787f705a32680c8e59560 HEAD; then
	      _patchname='proton-tkg-additions-ad5cb83.patch' && _patchmsg="Using additional Proton-tkg patches" && nonuser_patcher
	    else
	      _patchname='proton-tkg-additions-6be2138.patch' && _patchmsg="Using additional Proton-tkg patches" && nonuser_patcher
	    fi
	  fi
      source "$_where"/wine-tkg-patches/proton-tkg-specific/proton-pa/proton-pa
      source "$_where"/wine-tkg-patches/proton-tkg-specific/proton-gstreamer/proton-gstreamer
      source "$_where"/wine-tkg-patches/proton-tkg-specific/proton-windows.gaming.input/proton-windows.gaming.input
      source "$_where"/wine-tkg-patches/proton/proton-tabtip/proton-tabtip
	fi
