#!/bin/bash

# https://bugs.winehq.org/show_bug.cgi?id=51687 - https://bugs.winehq.org/attachment.cgi?id=70579&action=diff
if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor af4378d46dbb72e682017485212442bf865c2226 HEAD ); then
  warning "Hotfix: Fix for Riot Client updates"
  _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/GetMappedFileName/Return_nt_filename_and_resolve_DOS_drive_path)
elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 8e2df64cf8979334618a3e2672d19cb9b891fa3f HEAD ); then
  warning "Hotfix: Fix for Riot Client updates"
  _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/GetMappedFileName/Return_nt_filename_and_resolve_DOS_drive_path-af4378d)
fi
