#!/bin/bash

# Revert 789c1db1, which breaks -at least- The Witcher 3
if ( cd "${srcdir}"/"${_winesrcdir}" && ! git merge-base --is-ancestor 1722615b06cba2f04fcd0ca69bbc33d963fb143f HEAD ); then
  if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 9561af9a7d8d77e2f98341e278c842226cae47ed HEAD ); then
    warning "Hotfix: Fix The Witcher 3, Borderlands 3, Nioh 2 crashing since 789c1db1 - Patch by Rémi Bernon"
    _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/the_witcher_iii/virtual_alloc_remi2)
  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 6de7fa1bde015d8c6d1743dec7c04a9f5652e788 HEAD ); then
    warning "Hotfix: Fix The Witcher 3, Borderlands 3, Nioh 2 crashing since 789c1db1 - Patch by Rémi Bernon"
    _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/the_witcher_iii/virtual_alloc_remi)
  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 789c1db18a4e192425da3771cac4726cda77130b HEAD ); then
    warning "Hotfix: Revert 789c1db1 as it breaks -at least- The Witcher 3"
    _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/the_witcher_iii/revert_789c1db1)
  fi
fi
