#!/bin/bash

if [ "$_use_staging" = "true" ] && ( cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor 66561ecf5d66c03af6360e38b3c339a2bd72ba3e HEAD ); then
  warning "Hotfix: Add python3 compat for staging's patchinstall.py"
  _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/staging_patchinstall.py/python3_compat)
fi
