#!/bin/bash

	# Proton Battleye
	if [ "$_proton_battleye_support" = "true" ] && [ "$_unfrog" != "true" ]; then
	  if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 15bf49bf9b938eadd1368922a2d8e2c71824049d HEAD ); then
	    _patchname='proton_battleye.patch' && _patchmsg="Add support for Proton's Battleye runtime" && nonuser_patcher
	  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 12d33d21d33788fd46898ea42e9592d33b6e7c8e HEAD ); then
	    _patchname='proton_battleye-15bf49b.patch' && _patchmsg="Add support for Proton's Battleye runtime" && nonuser_patcher
	  fi
	fi
