#!/bin/bash

	# Workarounds to prevent crashes on some mf functions
	if ! git merge-base --is-ancestor 437bc14ac352df8b34819f7df6aab0b0fb04dddd HEAD; then
	  if [ "$_use_staging" = "true" ] && [ "$_proton_mf_hacks" = "true" ] && git merge-base --is-ancestor b182ba882cfcce7b8769470f49f0fba216095c45 HEAD; then
	    if git merge-base --is-ancestor e308d81a617632fe0fedd243952f79e8d9ec05b4 HEAD; then
	      _patchname='proton_mf_hacks.patch' && _patchmsg="Applied proton mf hacks patch" && nonuser_patcher
	    elif git merge-base --is-ancestor f540d1615fe66c95a3824e86e5292a026511749e HEAD; then
	      _patchname='proton_mf_hacks-e308d81.patch' && _patchmsg="Applied proton mf hacks patch" && nonuser_patcher
	    elif git merge-base --is-ancestor 120505ed6b590daea11486a512dd563600d0329f HEAD; then
	      _patchname='proton_mf_hacks-f540d16.patch' && _patchmsg="Applied proton mf hacks patch" && nonuser_patcher
	    elif git merge-base --is-ancestor 7c5fcfffe7b3a001c980f19cb6ed1cee049c26c8 HEAD; then
	      _patchname='proton_mf_hacks-120505e.patch' && _patchmsg="Applied proton mf hacks patch" && nonuser_patcher
	    else
	      _patchname='proton_mf_hacks-7c5fcff.patch' && _patchmsg="Applied proton mf hacks patch" && nonuser_patcher
	    fi
	  fi
	fi
