#!/bin/bash

# Rebase of this Proton patch to work around peek_message + shared memory: https://github.com/ValveSoftware/wine/commit/9ceae59cebd111f0fb06d63ad1495ea1becd714b
if [ "$_use_esync" = "true" ] && ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 54ca1ab607d3ff22a1f57a9561430f64c75f0916 HEAD ); then
  warning "Hotfix: Fix for high CPU usage with esync/fsync"
  _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/shm_esync_fsync/HACK-user32-Always-call-get_message-request-after-waiting)
fi
