#!/bin/bash

if [ "$_sdl_joy_support" = "true" ] && ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 872dc83e81c942d17a39700c4b520a6e92ddbdf2 HEAD ); then
  warning "Workaround configure error regarding missing js_blacklist header on staging"
  _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/js_blacklist-fix/js_blacklist-fix)
fi
