#!/bin/bash

# https://bugs.winehq.org/show_bug.cgi?id=51222#c2 - Multiple games have rendering issues caused by import of logf from musl (Kingdom Come: Deliverance, Just Cause 4, Wizard101)
if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 51a253d25a65be68f25d20844548d8272ee0a5c4 HEAD && ! git merge-base --is-ancestor 673815e0edb7a3a505b8a8b39a79f97c8ce8fc32 HEAD ); then
  warning "Hotfix: Fix multiple games having rendering issues (Kingdom Come: Deliverance, Just Cause 4, Wizard101) - Patch by Piotr Caban"
  _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/logf/msvcrt_Fix_logf_implementation)
fi
