#!/bin/bash

	# Set a custom fake refresh rate for virtual desktop
	if [ -n "$_fake_refresh_rate" ] && ( ! git merge-base --is-ancestor 6f305dd881e16f77f9eb183684d04b0b8746b769 HEAD || [ "$_proton_fs_hack" = "true" ] ); then
	  sed -i "s/999999/$_fake_refresh_rate/g" "${_where}/virtual_desktop_refreshrate.patch"
	  _patchname='virtual_desktop_refreshrate.patch' && _patchmsg="Applied custom fake virtual desktop refresh rate ($_fake_refresh_rate Hz) patch" && nonuser_patcher
	fi
