#!/bin/bash

	# Low latency alsa audio - https://blog.thepoon.fr/osuLinuxAudioLatency/
	if [ "$_lowlatency_audio" = "true" ] && [ "$_use_staging" = "true" ]; then
	  if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor b08d7efa5e8e62f995b2e65fc18d139b7d8a9d57 HEAD ); then
	    _patchname='lowlatency_audio.patch' && _patchmsg="Applied low latency alsa audio patch" && nonuser_patcher
	  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 253b1325b4a8ffc02e0c05e336c201ae8bbb3705 HEAD ); then
	    _patchname='lowlatency_audio-b08d7ef.patch' && _patchmsg="Applied low latency alsa audio patch" && nonuser_patcher
	  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 71d0cdde89af4b28d29b74adbe67942f5d7c24d7 HEAD ); then
	    _patchname='lowlatency_audio-253b132.patch' && _patchmsg="Applied low latency alsa audio patch" && nonuser_patcher
	  else
	    _patchname='lowlatency_audio-71d0cdd.patch' && _patchmsg="Applied low latency alsa audio patch" && nonuser_patcher
	  fi
	fi

	# Low latency pulse/pipewire audio - https://blog.thepoon.fr/osuLinuxAudioLatency/
	if [ "$_lowlatency_audio_pulse" = "true" ]; then
	  if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 5302181eb0b71cc378306e6ec3b304a95d423ba8 HEAD ); then
	    _patchname='lowlatency_audio_pulse.patch' && _patchmsg="Applied low latency pulse/pipewire audio patch" && nonuser_patcher
	  elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor f77af3dd6324fadaf153062d77b51f755f71faea HEAD ); then
	    _patchname='lowlatency_audio_pulse-5302181.patch' && _patchmsg="Applied low latency pulse/pipewire audio patch" && nonuser_patcher
	  fi
	fi
