#!/bin/bash

	# IMAGE_FILE_LARGE_ADDRESS_AWARE override - Enable with WINE_LARGE_ADDRESS_AWARE=1
	if [ "$_large_address_aware" = "true" ]; then
		if [ "$_NOLIB32" != "wow64" ]; then
			if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 8cba5b8e0f58b529de71db529882aa358ee8fbb4 HEAD ); then
				if [ "$_use_staging" = "true" ]; then
					_patchname='LAA-unix-staging-wow64.patch' && _patchmsg="Applied large address aware override support" && nonuser_patcher
				else
					_patchname='LAA-unix-wow64.patch' && _patchmsg="Applied large address aware override support" && nonuser_patcher
				fi
			elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor e377b7406859213adda6ccf912a4b64753fe88b3 HEAD ); then
				if [ "$_use_staging" = "true" ]; then
					_patchname='LAA-unix-staging-wow64-8cba5b8e.patch' && _patchmsg="Applied large address aware override support" && nonuser_patcher
				else
					_patchname='LAA-unix-wow64-8cba5b8e.patch' && _patchmsg="Applied large address aware override support" && nonuser_patcher
				fi
			elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor ea19c0604abe4c8b41e45a8759e4f335c5d0c50d HEAD ); then
				if [ "$_use_staging" = "true" ]; then
					_patchname='LAA-unix-staging-wow64-e377b74.patch' && _patchmsg="Applied large address aware override support" && nonuser_patcher
				else
					_patchname='LAA-unix-wow64-e377b74.patch' && _patchmsg="Applied large address aware override support" && nonuser_patcher
				fi
			elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor f9f23e109287b86bf3d1703cad374326c1eb4ccd HEAD ); then
				if [ "$_use_staging" = "true" ]; then
				_patchname='LAA-unix-staging.patch' && _patchmsg="Applied large address aware override support (legacy)" && nonuser_patcher
				else
				_patchname='LAA-unix.patch' && _patchmsg="Applied large address aware override support (legacy)" && nonuser_patcher
				fi
			elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor a81c53504ae32715e6e91bd020fdebd5bef20d48 HEAD ); then
				if [ "$_use_staging" = "true" ]; then
				_patchname='LAA-unix-staging-f9f23e1.patch' && _patchmsg="Applied large address aware override support (legacy)" && nonuser_patcher
				else
				_patchname='LAA-unix-f9f23e1.patch' && _patchmsg="Applied large address aware override support (legacy)" && nonuser_patcher
				fi
			elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 46d0da53b61254d52aa86c6cb524609110cb1213 HEAD ); then
				if [ "$_use_staging" = "true" ]; then
				_patchname='LAA-unix-staging-a81c535.patch' && _patchmsg="Applied large address aware override support (legacy)" && nonuser_patcher
				else
				_patchname='LAA-unix-a81c535.patch' && _patchmsg="Applied large address aware override support (legacy)" && nonuser_patcher
				fi
			elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor ee147d92160cf61cdf808df6fad277198b37a0d4 HEAD ); then
				if [ "$_use_staging" = "true" ]; then
				_patchname='LAA-unix-staging-46d0da5.patch' && _patchmsg="Applied large address aware override support (legacy)" && nonuser_patcher
				else
				_patchname='LAA-unix-46d0da5.patch' && _patchmsg="Applied large address aware override support (legacy)" && nonuser_patcher
				fi
			elif git merge-base --is-ancestor c998667bf0983ef99cc48847d3d6fc6ca6ff4a2d HEAD && ! git merge-base --is-ancestor 9f0d66923933d82ae0b09fe5d84f977c1a657cc1 HEAD; then
				if [ "$_use_staging" = "true" ]; then
				_patchname='legacy-LAA-staging.patch' && _patchmsg="Applied large address aware override support (legacy)" && nonuser_patcher
				else
				_patchname='legacy-LAA.patch' && _patchmsg="Applied large address aware override support (legacy)" && nonuser_patcher
				fi
			elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor ea6308e364b669adfcb8b1e448c8b08d715bcf6d HEAD ); then
				if [ "$_use_staging" = "true" ]; then
				_patchname='LAA-unix-staging-ee147d9.patch' && _patchmsg="Applied large address aware override support" && nonuser_patcher
				else
				_patchname='LAA-unix-ee147d9.patch' && _patchmsg="Applied large address aware override support" && nonuser_patcher
				fi
			elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor ac3ec2d955573e187413743428ee7e4d1a6906d5 HEAD ); then
				if [ "$_use_staging" = "true" ]; then
				_patchname='LAA-unix-staging-ea6308e.patch' && _patchmsg="Applied large address aware override support" && nonuser_patcher
				else
				_patchname='LAA-unix-ea6308e.patch' && _patchmsg="Applied large address aware override support" && nonuser_patcher
				fi
			elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 72c562ce9c481e73a01f50e17b624095aab11bdc HEAD ); then
				if [ "$_use_staging" = "true" ]; then
				_patchname='LAA-unix-staging-ac3ec2d.patch' && _patchmsg="Applied large address aware override support" && nonuser_patcher
				else
				_patchname='LAA-unix-ac3ec2d.patch' && _patchmsg="Applied large address aware override support" && nonuser_patcher
				fi
			elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 7512c53b89308c16a512cb8f0c1d0fd6ff02b17b HEAD ); then
				if [ "$_use_staging" = "true" ]; then
				_patchname='LAA-unix-staging-72c562c.patch' && _patchmsg="Applied large address aware override support" && nonuser_patcher
				else
				_patchname='LAA-unix-72c562c.patch' && _patchmsg="Applied large address aware override support" && nonuser_patcher
				fi
			elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 0c249e6125fc9dc6ee86b4ef6ae0d9fa2fc6291b HEAD ); then
				if [ "$_use_staging" = "true" ]; then
				_patchname='LAA-unix-staging-7512c53.patch' && _patchmsg="Applied large address aware override support" && nonuser_patcher
				else
				_patchname='LAA-unix-7512c53.patch' && _patchmsg="Applied large address aware override support" && nonuser_patcher
				fi
			elif git merge-base --is-ancestor 18411a19b4ea3a68234980c56d4c252670dfc000 HEAD; then
				if [ "$_use_staging" = "true" ]; then
				_patchname='LAA-staging.patch' && _patchmsg="Applied large address aware override support" && nonuser_patcher
				else
				_patchname='LAA.patch' && _patchmsg="Applied large address aware override support" && nonuser_patcher
				fi
			elif git merge-base --is-ancestor 608d086f1b1bb7168e9322c65224c23f34e75f29 HEAD; then
				if [ "$_use_staging" = "true" ]; then
				_patchname='LAA-staging-18411a1.patch' && _patchmsg="Applied large address aware override support" && nonuser_patcher
				else
				_patchname='LAA-18411a1.patch' && _patchmsg="Applied large address aware override support" && nonuser_patcher
				fi
			elif git merge-base --is-ancestor 9f0d66923933d82ae0b09fe5d84f977c1a657cc1 HEAD; then
				if [ "$_use_staging" = "true" ]; then
				_patchname='LAA-staging-608d086.patch' && _patchmsg="Applied large address aware override support" && nonuser_patcher
				else
				_patchname='LAA-608d086.patch' && _patchmsg="Applied large address aware override support" && nonuser_patcher
				fi
			fi
		elif [ "$_NOLIB32" = "wow64" ]; then
			if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 8cba5b8e0f58b529de71db529882aa358ee8fbb4 HEAD ); then
				if [ "$_use_staging" = "true" ]; then
					_patchname='LAA-unix-staging-wow64.patch' && _patchmsg="Applied large address aware override support" && nonuser_patcher
				else
					_patchname='LAA-unix-wow64.patch' && _patchmsg="Applied large address aware override support" && nonuser_patcher
				fi
			elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor e377b7406859213adda6ccf912a4b64753fe88b3 HEAD ); then
				if [ "$_use_staging" = "true" ]; then
					_patchname='LAA-unix-staging-wow64-8cba5b8e.patch' && _patchmsg="Applied large address aware override support" && nonuser_patcher
				else
					_patchname='LAA-unix-wow64-8cba5b8e.patch' && _patchmsg="Applied large address aware override support" && nonuser_patcher
				fi
			elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor ea19c0604abe4c8b41e45a8759e4f335c5d0c50d HEAD ); then
				if [ "$_use_staging" = "true" ]; then
					_patchname='LAA-unix-staging-wow64-e377b74.patch' && _patchmsg="Applied large address aware override support" && nonuser_patcher
				else
					_patchname='LAA-unix-wow64-e377b74.patch' && _patchmsg="Applied large address aware override support" && nonuser_patcher
				fi
			elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor ee147d92160cf61cdf808df6fad277198b37a0d4 HEAD ); then
				if [ "$_use_staging" = "true" ]; then
					_patchname='LAA-unix-staging-wow64-ea19c06.patch' && _patchmsg="Applied large address aware override support" && nonuser_patcher
				else
					_patchname='LAA-unix-wow64-ea19c06.patch' && _patchmsg="Applied large address aware override support" && nonuser_patcher
				fi
			fi
		fi
	fi
