#!/bin/bash

# FC New Dawn hotfix - https://bugs.winehq.org/show_bug.cgi?id=51990
if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 1a02b3f1c6dbe1cb342f7e9066116eba9bcf6c85 HEAD ); then
  _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/RtlGetCurrentUmsThread/Stub_RtlGetCurrentUmsThread)
fi
