#!/bin/bash

	# Update winevulkan
	if [ "$_GE_WAYLAND" = "true" ] && git merge-base --is-ancestor 0ac1033f04074339de5cae9ffd9f4f45baaef92e HEAD; then
	  _patchname='0025-support-older-EGL-headers.patch' && _patchmessage='Applied winewayland hotfixes' &&nonuser_patcher
	  _patchname='0028-hack-winewayland-handle-fractional-scaling.patch' && nonuser_patcher
	  _patchname='0029-cursor-shape-v1.patch' && nonuser_patcher
	  _patchname='0030-Avoid-long-types-on-the-Unix-side.patch' && nonuser_patcher
	  _patchname='0032-winewayland-ensure-egl_display-is-not-EGL_BAD_PARAME.patch' && nonuser_patcher
	  _patchname='0033-Add-amdxc-implementation.patch' && nonuser_patcher
	  _patchname='0040-check-if-FSR4_UPGRADE-env-is-nonzero.patch' && nonuser_patcher
	  _patchname='0041-fixup-winewayland-handle-locking-with-fractional-sca.patch' && nonuser_patcher
	  _patchname='0044-minor-formatting-fix.patch' && nonuser_patcher
	fi
