#!/bin/bash

	# Update winevulkan
	if [ "$_GE_WAYLAND" = "true" ]; then
	  _patchmessage='Applied winewayland hotfixes'
	  if ( cd "${srcdir}"/"${_winesrcdir}" ) && git merge-base --is-ancestor 76ad9185a5f1907977603d570844843ff51edb9b HEAD; then
	    _patchname='ge-wayland.patch' && nonuser_patcher
	  elif ( cd "${srcdir}"/"${_winesrcdir}" ) && git merge-base --is-ancestor daa5b0b690d6dcbef8a0aec63478d3c5b7bce573 HEAD; then
	    _patchname='ge-wayland-76ad9185.patch' && nonuser_patcher
	  elif ( cd "${srcdir}"/"${_winesrcdir}" ) && git merge-base --is-ancestor 0ac1033f04074339de5cae9ffd9f4f45baaef92e HEAD; then
	    _patchname='ge-wayland-daa5b0b6.patch' && nonuser_patcher
	  fi
	fi
