#!/bin/bash

# Autoconf 2.70 fix for legacy trees - https://github.com/wine-mirror/wine/commit/d7645b67c350f7179a1eba749ec4524c74948d86
if ( cd "${srcdir}"/"${_winesrcdir}" && ! git merge-base --is-ancestor d7645b67c350f7179a1eba749ec4524c74948d86 HEAD ); then
  warning "Hotfix: Fix for legacy trees when using autoconf 2.70"
  _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/autoconf-legacy-fix/autoconf-legacy-fix)
fi
