#!/bin/bash
	  if [ "$_proton_winevulkan" = "true" ] && git merge-base --is-ancestor b073859675060c9211fcbccfd90e4e87520dc2c2 HEAD; then
	    if [ "$_protonify" = "false" ]; then
	      _patchname='vulkan-1-Prefer-builtin.patch' && _patchmsg="Prefer build vulkan-1 patch" && nonuser_patcher
		fi
		if [ "$_use_ntsync" = "legacy" ]; then
		  _patchname='ntoskrnl-server-Support-referencing-section-objects-ntsync.patch' && _patchmsg="ntoskrnl, server: Support referencing section objects. (Ntsync)" && nonuser_patcher
		else
		  if git merge-base --is-ancestor 8c4c4264c1f13191988632b49a58734919f922a5 HEAD; then
		    _patchname='ntoskrnl-server-Support-referencing-section-objects.patch' && _patchmsg="ntoskrnl, server: Support referencing section objects. (Server side)" && nonuser_patcher
		  else
		    _patchname='ntoskrnl-server-Support-referencing-section-objects-8c4c4264.patch' && _patchmsg="ntoskrnl, server: Support referencing section objects. (Server side)" && nonuser_patcher
		  fi
		fi

		if git merge-base --is-ancestor eb654654d26b2afe778915f73bd0af1d47cb9fe2 HEAD; then
	      _patchname='proton10-winevulkan.patch' && _patchmsg="Using Proton 10 winevulkan patches" && nonuser_patcher
		else
		  if git merge-base --is-ancestor ae65372986a33040c8040bc30ceb760d9d9bf5d3 HEAD; then
		    _lastcommit="eb654654"
		  elif git merge-base --is-ancestor 69e95495a99acd4d1973e97e51b660705de72cf3 HEAD; then
		    _lastcommit="ae653729"
		  elif git merge-base --is-ancestor 17b7f4fcec3bf88efe42ad22af5f19ef278c4380 HEAD; then
		    _lastcommit="69e95495"
		  elif git merge-base --is-ancestor 9b07617c95ae2d5168c0421d15092da150fc84cf HEAD; then
		    _lastcommit="17b7f4fc"
		  elif git merge-base --is-ancestor 44bd863e5316388e83e835fd80e9790a01754dfc HEAD; then
		    _lastcommit="9b07617c"
		  elif git merge-base --is-ancestor 4f17e8dff389b6679314ab9ce07e91c2dcb0921d HEAD; then
		    _lastcommit="44bd863e"
		  elif git merge-base --is-ancestor 0992b2eaacbd1627a36eb699ce08c0e8c6d06e3b HEAD; then
		    _lastcommit="4f17e8df"
		  elif git merge-base --is-ancestor e10b4254408a5b64e725fbf823cc80efe7e3956f HEAD; then
		    _lastcommit="0992b2ea"
		  elif git merge-base --is-ancestor 6a663cc9d23ae64c9bc85a0f2789d7ee5c79f60c HEAD; then
		    _lastcommit="e10b4254"
		  elif git merge-base --is-ancestor 6a663cc9d23ae64c9bc85a0f2789d7ee5c79f60c HEAD; then
		    _lastcommit="f3feb131"
		  elif git merge-base --is-ancestor 061232d85b2ee283f785741f68caca107ac64537 HEAD; then
		    _lastcommit="6a663cc9"
		  elif git merge-base --is-ancestor 08fabc1d6a7a7bfc23e4292cd7c7af167ec1bf29 HEAD; then
		    _lastcommit="061232d8"
		  elif git merge-base --is-ancestor 751f6574c06efe7012c841ca91ba4065e8c873a7 HEAD; then
		    _lastcommit="08fabc1d"
		  elif git merge-base --is-ancestor 4f2b2833ab87f375360d01427349c1cd22b9791b HEAD; then
		    _lastcommit="751f6574"
		  elif git merge-base --is-ancestor e00685940360a351cd75347fdce1276d698b6884 HEAD; then
		    _lastcommit="4f2b2833"
		  elif git merge-base --is-ancestor b073859675060c9211fcbccfd90e4e87520dc2c2 HEAD; then
		    _lastcommit="e0068594"
		  else
		    _lastcommit="none"
		  fi
		  if [ "$_lastcommit" != "none" ]; then
		  _patchname="proton10-winevulkan-$_lastcommit.patch" && _patchmsg="Using Proton 10 winevulkan patches" && nonuser_patcher
		  fi
		fi
	  fi

	  # Legacy patches for wine
	  if [ "$_update_winevulkan" = "true" ] && git merge-base --is-ancestor 7e736b5903d3d078bbf7bb6a509536a942f6b9a0 HEAD && ! git merge-base --is-ancestor  656edbb508d51cbe3155d856ee3f2c27a6cd4cba HEAD && ( ! git merge-base --is-ancestor 0f972e2247932f255f131792724e4796b4b2b87a HEAD || git merge-base --is-ancestor 21e002aa7e7f85d92d1efeaeb7a9545eb16b96ad HEAD && [ "$_proton_fs_hack" = "true" ] ); then
	    if git merge-base --is-ancestor 221995a6838da5be2217735c3b1e1b1cd8f01e9f HEAD; then
	      if [ "$_proton_fs_hack" = "true" ]; then
	        _patchname='proton-winevulkan.patch' && _patchmsg="Using Proton winevulkan patches" && nonuser_patcher
	      else
	        _patchname='proton-winevulkan-nofshack.patch' && _patchmsg="Using Proton winevulkan patches (nofshack)" && nonuser_patcher
	      fi
	    else
	      if git merge-base --is-ancestor 8285f616030f27877922ff414530d4f909306ace HEAD; then
	        _lastcommit="221995a"
	      elif git merge-base --is-ancestor 9561af9a7d8d77e2f98341e278c842226cae47ed HEAD; then
	        _lastcommit="8285f61"
	      elif git merge-base --is-ancestor 88da78ef428317ff8c258277511abebf1a75e186 HEAD; then
	        _lastcommit="9561af9"
	      elif git merge-base --is-ancestor c681a0732fc3c6466b228417bb5e0d518d26b819 HEAD; then
	        _lastcommit="88da78e"
	      elif git merge-base --is-ancestor eb9f3dd3ad07aae3c9588bcff376ed2a7a8ef8d2 HEAD; then
	        _lastcommit="c681a07"
	      elif git merge-base --is-ancestor 7d8c50e4371f2fc5300b90b323210c922d80d4e9 HEAD; then
	        _lastcommit="eb9f3dd"
	      elif git merge-base --is-ancestor fc893489fe89c9fbd22f0cbe1c4327c64f05e0dc HEAD; then
	        _lastcommit="7d8c50e"
	      elif git merge-base --is-ancestor bff6bc6a79ffc3a915219a6dfe64c9bcabaaeceb HEAD; then
	        _lastcommit="fc89348"
	      elif git merge-base --is-ancestor 1e074c39f635c585595e9f3ece99aa290a7f9cf8 HEAD; then
	        _lastcommit="bff6bc6"
	      elif git merge-base --is-ancestor 8bd62231c3ab222c07063cb340e26c3c76ff4229 HEAD; then
	        _lastcommit="1e074c3"
	      elif git merge-base --is-ancestor 380b7f28253c048d04c1fbd0cfbc7e804bb1b0e1 HEAD; then
	        _lastcommit="8bd6223"
	      elif git merge-base --is-ancestor 408a5a86ec30e293bf9e6eec4890d552073a82e8 HEAD; then
	        _lastcommit="380b7f2"
	      elif git merge-base --is-ancestor d2f552d1508dbabb595eae23db9e5c157eaf9b41 HEAD; then
	        _lastcommit="408a5a8"
	      elif git merge-base --is-ancestor 594814c00ab059d9686ed836b1865f8a94859c8a HEAD; then
	        _lastcommit="d2f552d"
	      elif git merge-base --is-ancestor 086c686e817a596e35c41dd5b37f3c28587af9d5 HEAD; then
	        _lastcommit="594814c"
	      elif git merge-base --is-ancestor bdeae71bc129ac83c44753672d110b06a480c93c HEAD; then
	        _lastcommit="086c686"
	      elif git merge-base --is-ancestor 7b1622d1ab90f01fdb3a2bc24e12ab4990f07f68 HEAD; then
	        _lastcommit="bdeae71"
	      #elif git merge-base --is-ancestor 7e736b5903d3d078bbf7bb6a509536a942f6b9a0 HEAD; then
	      #  _lastcommit="7b1622d"
	      else
	        _lastcommit="none"
	      fi
	      if [ "$_lastcommit" != "none" ]; then
	        if [ "$_proton_fs_hack" = "true" ]; then
	          _patchname="proton-winevulkan-$_lastcommit.patch" && _patchmsg="Using Proton winevulkan patches" && nonuser_patcher
	        else
	          _patchname="proton-winevulkan-nofshack-$_lastcommit.patch" && _patchmsg="Using Proton winevulkan patches (nofshack)" && nonuser_patcher
	        fi
          fi
	    fi
	  fi
