#!/bin/bash

# Selective reverts to fix steamclient swap on proton
if (cd "${srcdir}"/"${_winesrcdir}" && ! git merge-base --is-ancestor ba74c5c6984bb19aade5ae0dfaa71b0f77d5786e HEAD ); then
  if [ "$_use_staging" = "true" ] && [ "$_EXTERNAL_INSTALL" = "proton" ] && ( cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor be3928a8091e36197bc9894c4a09f13cf5459138 HEAD ); then
    _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/steamclient_swap/staging-server-default-integrity)
  fi
  if [ "$_EXTERNAL_INSTALL" = "proton" ] && ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor bb065801a693e1cd305d2a507c206f1b21a142d3 HEAD ); then
    warning "Hotfix: Fix for steamclient swap breakage"
    # steam_helper broke with 4e8fcc4 - Restore __wine_make_process_system to make it happy
    if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 4e8fcc41ca42f7e047e4a5cb708a75447a753143 HEAD ); then
      if (cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor ba74c5c6984bb19aade5ae0dfaa71b0f77d5786e HEAD ); then
        _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/steamclient_swap/revert_steamclient_breaker15)
      elif ( [ "$_use_staging" = "true" ] && [ "$_protonify" = "true" ] && cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 5c009c17b3a212c3f5b0034c465077c0c593daae HEAD && ! git merge-base --is-ancestor 20fff538c49c87abffd583f6b63371592ebdd835 HEAD ); then
        _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/steamclient_swap/revert_steamclient_breaker14-proton)
      else
        _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/steamclient_swap/revert_steamclient_breaker14)
      fi
      # Add __wine_make_process_system syscall to ntdll loader array following ea6308e364b669adfcb8b1e448c8b08d715bcf6d
      if (cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor ea6308e364b669adfcb8b1e448c8b08d715bcf6d HEAD ); then
        if [ "$_large_address_aware" = "true" ]; then
          _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/steamclient_swap/add_syscall_to_loader_array)
        else
          _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/steamclient_swap/add_syscall_to_loader_array-noLAA)
        fi
      fi
    fi
    if ( cd "${srcdir}"/"${_winesrcdir}" && ! git merge-base --is-ancestor 9561af9a7d8d77e2f98341e278c842226cae47ed HEAD ); then
      if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 78cbc269572b4a7e5e7cfcf4e063a023fcff2cba HEAD ); then
        _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/steamclient_swap/revert_steamclient_breaker13)
      elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 1e5eee0fc318459d7ef071998e8ed05f2530d2c3 HEAD ); then
        _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/steamclient_swap/revert_steamclient_breaker12)
      elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 5ba8f0d73b27e5df7ce40c0413743cb917405d0e HEAD ); then
        _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/steamclient_swap/revert_steamclient_breaker11)
      elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 4dca2cc797c9951531257d9bd69f8c24c71b6c2b HEAD ); then
        _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/steamclient_swap/revert_steamclient_breaker10)
      elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor e9bc48e90a7f31820e3c1171cc6bbdc13a650b8f HEAD ); then
        _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/steamclient_swap/revert_steamclient_breaker9)
      elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor d47a711e986342a0f6b9fe520f2a34378877cd61 HEAD ); then
        _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/steamclient_swap/revert_steamclient_breaker8)
      elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 620c0818bfa4554ee6d44ec2433c25ece598746b HEAD ); then
        _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/steamclient_swap/revert_steamclient_breaker7)
      elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 893febda143ccf4e4499d411fd28ab2f225aea09 HEAD ); then
        _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/steamclient_swap/revert_steamclient_breaker6)
      elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor aaa501fe93fb7140b472850060d652613406307f HEAD ); then
        _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/steamclient_swap/revert_steamclient_breaker5)
      elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 277a5728da6cdce0247521dc63b324e120b542d6 HEAD ); then
        _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/steamclient_swap/revert_steamclient_breaker4)
      elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 0bbbf016b1eb1c90a98c58afc2760319050a04d3 HEAD ); then
        _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/steamclient_swap/revert_steamclient_breaker3)
      elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 42de71c38780931c510ada6d7ee8681c99bbc60b HEAD ); then
        _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/steamclient_swap/revert_steamclient_breaker2)
      elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor f55f0b8448b6810f583784235d809bdbb10b2d6d HEAD ); then
        _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/steamclient_swap/revert_steamclient_breaker1)
      elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor bb065801a693e1cd305d2a507c206f1b21a142d3 HEAD ); then
        _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/steamclient_swap/revert_steamclient_breaker0)
      fi
    fi
  fi
  _no_loader_array="true"
fi
