#!/bin/bash

# Fix regression causing failed building with mkdir ""
if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 7620f21ff98a85249b0b110bcba9953b32763f28 HEAD ); then
  _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/makefiles/7371)
  warning "Hotfix: Fix regression causing failed building"
fi
